# dockflow-artifact: k8s-manifests/1
# stack: shop-production
# role: app
# version: 1.4.2
---
apiVersion: v1
kind: Service
metadata:
  name: ss-a
  namespace: dockflow-shop-production
  annotations:
    dockflow.shawiizz.dev/compose-service: ss-a
  labels:
    app.kubernetes.io/instance: dockflow-shop-production
    app.kubernetes.io/managed-by: dockflow
    app.kubernetes.io/name: ss-a
    app.kubernetes.io/part-of: shop
    dockflow.shawiizz.dev/part: stack
    dockflow.shawiizz.dev/role: app
    dockflow.shawiizz.dev/service: ss-a
    dockflow.shawiizz.dev/stack: dockflow-shop-production
spec:
  clusterIP: None
  ports:
    - name: placeholder
      port: 9
      protocol: TCP
  selector:
    dockflow.shawiizz.dev/service: ss-a
    dockflow.shawiizz.dev/stack: dockflow-shop-production
---
apiVersion: v1
kind: Service
metadata:
  name: ss-a-hl
  namespace: dockflow-shop-production
  annotations:
    dockflow.shawiizz.dev/compose-service: ss-a
  labels:
    app.kubernetes.io/instance: dockflow-shop-production
    app.kubernetes.io/managed-by: dockflow
    app.kubernetes.io/name: ss-a
    app.kubernetes.io/part-of: shop
    dockflow.shawiizz.dev/part: stack
    dockflow.shawiizz.dev/role: app
    dockflow.shawiizz.dev/service: ss-a
    dockflow.shawiizz.dev/stack: dockflow-shop-production
spec:
  clusterIP: None
  ports:
    - name: placeholder
      port: 9
      protocol: TCP
  selector:
    dockflow.shawiizz.dev/service: ss-a
    dockflow.shawiizz.dev/stack: dockflow-shop-production
---
apiVersion: v1
kind: Service
metadata:
  name: ss-b
  namespace: dockflow-shop-production
  annotations:
    dockflow.shawiizz.dev/compose-service: ss-b
  labels:
    app.kubernetes.io/instance: dockflow-shop-production
    app.kubernetes.io/managed-by: dockflow
    app.kubernetes.io/name: ss-b
    app.kubernetes.io/part-of: shop
    dockflow.shawiizz.dev/part: stack
    dockflow.shawiizz.dev/role: app
    dockflow.shawiizz.dev/service: ss-b
    dockflow.shawiizz.dev/stack: dockflow-shop-production
spec:
  clusterIP: None
  ports:
    - name: tcp-80
      port: 80
      protocol: TCP
  selector:
    dockflow.shawiizz.dev/service: ss-b
    dockflow.shawiizz.dev/stack: dockflow-shop-production
---
apiVersion: v1
kind: Service
metadata:
  name: ss-b-hl
  namespace: dockflow-shop-production
  annotations:
    dockflow.shawiizz.dev/compose-service: ss-b
  labels:
    app.kubernetes.io/instance: dockflow-shop-production
    app.kubernetes.io/managed-by: dockflow
    app.kubernetes.io/name: ss-b
    app.kubernetes.io/part-of: shop
    dockflow.shawiizz.dev/part: stack
    dockflow.shawiizz.dev/role: app
    dockflow.shawiizz.dev/service: ss-b
    dockflow.shawiizz.dev/stack: dockflow-shop-production
spec:
  clusterIP: None
  ports:
    - name: tcp-80
      port: 80
      protocol: TCP
  selector:
    dockflow.shawiizz.dev/service: ss-b
    dockflow.shawiizz.dev/stack: dockflow-shop-production
---
apiVersion: v1
kind: Service
metadata:
  name: ss-b-lb
  namespace: dockflow-shop-production
  annotations:
    dockflow.shawiizz.dev/compose-service: ss-b
  labels:
    app.kubernetes.io/instance: dockflow-shop-production
    app.kubernetes.io/managed-by: dockflow
    app.kubernetes.io/name: ss-b
    app.kubernetes.io/part-of: shop
    dockflow.shawiizz.dev/part: stack
    dockflow.shawiizz.dev/role: app
    dockflow.shawiizz.dev/service: ss-b
    dockflow.shawiizz.dev/stack: dockflow-shop-production
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  ports:
    - name: tcp-80
      port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    dockflow.shawiizz.dev/service: ss-b
    dockflow.shawiizz.dev/stack: dockflow-shop-production
---
apiVersion: v1
kind: Service
metadata:
  name: ss-c
  namespace: dockflow-shop-production
  annotations:
    dockflow.shawiizz.dev/compose-service: ss-c
  labels:
    app.kubernetes.io/instance: dockflow-shop-production
    app.kubernetes.io/managed-by: dockflow
    app.kubernetes.io/name: ss-c
    app.kubernetes.io/part-of: shop
    dockflow.shawiizz.dev/part: stack
    dockflow.shawiizz.dev/role: app
    dockflow.shawiizz.dev/service: ss-c
    dockflow.shawiizz.dev/stack: dockflow-shop-production
spec:
  ports:
    - name: tcp-9090
      port: 9090
      protocol: TCP
  selector:
    dockflow.shawiizz.dev/service: ss-c
    dockflow.shawiizz.dev/stack: dockflow-shop-production
---
apiVersion: v1
kind: Service
metadata:
  name: ss-c-hl
  namespace: dockflow-shop-production
  annotations:
    dockflow.shawiizz.dev/compose-service: ss-c
  labels:
    app.kubernetes.io/instance: dockflow-shop-production
    app.kubernetes.io/managed-by: dockflow
    app.kubernetes.io/name: ss-c
    app.kubernetes.io/part-of: shop
    dockflow.shawiizz.dev/part: stack
    dockflow.shawiizz.dev/role: app
    dockflow.shawiizz.dev/service: ss-c
    dockflow.shawiizz.dev/stack: dockflow-shop-production
spec:
  clusterIP: None
  ports:
    - name: tcp-9090
      port: 9090
      protocol: TCP
  selector:
    dockflow.shawiizz.dev/service: ss-c
    dockflow.shawiizz.dev/stack: dockflow-shop-production
---
apiVersion: v1
kind: Service
metadata:
  name: ss-d
  namespace: dockflow-shop-production
  annotations:
    dockflow.shawiizz.dev/compose-service: ss-d
  labels:
    app.kubernetes.io/instance: dockflow-shop-production
    app.kubernetes.io/managed-by: dockflow
    app.kubernetes.io/name: ss-d
    app.kubernetes.io/part-of: shop
    dockflow.shawiizz.dev/part: stack
    dockflow.shawiizz.dev/role: app
    dockflow.shawiizz.dev/service: ss-d
    dockflow.shawiizz.dev/stack: dockflow-shop-production
spec:
  clusterIP: None
  ports:
    - name: placeholder
      port: 9
      protocol: TCP
  selector:
    dockflow.shawiizz.dev/service: ss-d
    dockflow.shawiizz.dev/stack: dockflow-shop-production
---
apiVersion: v1
kind: Service
metadata:
  name: ss-d-hl
  namespace: dockflow-shop-production
  annotations:
    dockflow.shawiizz.dev/compose-service: ss-d
  labels:
    app.kubernetes.io/instance: dockflow-shop-production
    app.kubernetes.io/managed-by: dockflow
    app.kubernetes.io/name: ss-d
    app.kubernetes.io/part-of: shop
    dockflow.shawiizz.dev/part: stack
    dockflow.shawiizz.dev/role: app
    dockflow.shawiizz.dev/service: ss-d
    dockflow.shawiizz.dev/stack: dockflow-shop-production
spec:
  clusterIP: None
  ports:
    - name: placeholder
      port: 9
      protocol: TCP
  selector:
    dockflow.shawiizz.dev/service: ss-d
    dockflow.shawiizz.dev/stack: dockflow-shop-production
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ss-a
  namespace: dockflow-shop-production
  annotations:
    dockflow.shawiizz.dev/compose-service: ss-a
  labels:
    app.kubernetes.io/instance: dockflow-shop-production
    app.kubernetes.io/managed-by: dockflow
    app.kubernetes.io/name: ss-a
    app.kubernetes.io/part-of: shop
    dockflow.shawiizz.dev/part: stack
    dockflow.shawiizz.dev/role: app
    dockflow.shawiizz.dev/service: ss-a
    dockflow.shawiizz.dev/stack: dockflow-shop-production
spec:
  minReadySeconds: 30
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      dockflow.shawiizz.dev/service: ss-a
      dockflow.shawiizz.dev/stack: dockflow-shop-production
  serviceName: ss-a-hl
  template:
    metadata:
      annotations:
        dockflow.shawiizz.dev/compose-service: ss-a
        kubectl.kubernetes.io/default-container: ss-a
      labels:
        app.kubernetes.io/instance: dockflow-shop-production
        app.kubernetes.io/name: ss-a
        dockflow.shawiizz.dev/role: app
        dockflow.shawiizz.dev/service: ss-a
        dockflow.shawiizz.dev/stack: dockflow-shop-production
    spec:
      automountServiceAccountToken: false
      containers:
        - name: ss-a
          image: nginx:1.27
          imagePullPolicy: IfNotPresent
      enableServiceLinks: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 10
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              dockflow.shawiizz.dev/service: ss-a
              dockflow.shawiizz.dev/stack: dockflow-shop-production
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
  updateStrategy:
    type: RollingUpdate
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ss-b
  namespace: dockflow-shop-production
  annotations:
    dockflow.shawiizz.dev/compose-service: ss-b
  labels:
    app.kubernetes.io/instance: dockflow-shop-production
    app.kubernetes.io/managed-by: dockflow
    app.kubernetes.io/name: ss-b
    app.kubernetes.io/part-of: shop
    dockflow.shawiizz.dev/part: stack
    dockflow.shawiizz.dev/role: app
    dockflow.shawiizz.dev/service: ss-b
    dockflow.shawiizz.dev/stack: dockflow-shop-production
spec:
  minReadySeconds: 30
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: Parallel
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      dockflow.shawiizz.dev/service: ss-b
      dockflow.shawiizz.dev/stack: dockflow-shop-production
  serviceName: ss-b-hl
  template:
    metadata:
      annotations:
        dockflow.shawiizz.dev/compose-service: ss-b
        kubectl.kubernetes.io/default-container: ss-b
      labels:
        app.kubernetes.io/instance: dockflow-shop-production
        app.kubernetes.io/name: ss-b
        dockflow.shawiizz.dev/role: app
        dockflow.shawiizz.dev/service: ss-b
        dockflow.shawiizz.dev/stack: dockflow-shop-production
    spec:
      automountServiceAccountToken: false
      containers:
        - name: ss-b
          image: nginx:1.27
          imagePullPolicy: IfNotPresent
          ports:
            - name: tcp-80
              containerPort: 80
              protocol: TCP
      enableServiceLinks: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 10
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              dockflow.shawiizz.dev/service: ss-b
              dockflow.shawiizz.dev/stack: dockflow-shop-production
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
  updateStrategy:
    type: RollingUpdate
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ss-c
  namespace: dockflow-shop-production
  annotations:
    dockflow.shawiizz.dev/compose-service: ss-c
  labels:
    app.kubernetes.io/instance: dockflow-shop-production
    app.kubernetes.io/managed-by: dockflow
    app.kubernetes.io/name: ss-c
    app.kubernetes.io/part-of: shop
    dockflow.shawiizz.dev/part: stack
    dockflow.shawiizz.dev/role: app
    dockflow.shawiizz.dev/service: ss-c
    dockflow.shawiizz.dev/stack: dockflow-shop-production
spec:
  minReadySeconds: 30
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      dockflow.shawiizz.dev/service: ss-c
      dockflow.shawiizz.dev/stack: dockflow-shop-production
  serviceName: ss-c-hl
  template:
    metadata:
      annotations:
        dockflow.shawiizz.dev/compose-service: ss-c
        kubectl.kubernetes.io/default-container: ss-c
      labels:
        app.kubernetes.io/instance: dockflow-shop-production
        app.kubernetes.io/name: ss-c
        dockflow.shawiizz.dev/role: app
        dockflow.shawiizz.dev/service: ss-c
        dockflow.shawiizz.dev/stack: dockflow-shop-production
    spec:
      automountServiceAccountToken: false
      containers:
        - name: ss-c
          image: nginx:1.27
          imagePullPolicy: IfNotPresent
          ports:
            - name: tcp-9090
              containerPort: 9090
              protocol: TCP
      enableServiceLinks: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 10
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              dockflow.shawiizz.dev/service: ss-c
              dockflow.shawiizz.dev/stack: dockflow-shop-production
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
  updateStrategy:
    type: RollingUpdate
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ss-d
  namespace: dockflow-shop-production
  annotations:
    dockflow.shawiizz.dev/compose-service: ss-d
  labels:
    app.kubernetes.io/instance: dockflow-shop-production
    app.kubernetes.io/managed-by: dockflow
    app.kubernetes.io/name: ss-d
    app.kubernetes.io/part-of: shop
    dockflow.shawiizz.dev/part: stack
    dockflow.shawiizz.dev/role: app
    dockflow.shawiizz.dev/service: ss-d
    dockflow.shawiizz.dev/stack: dockflow-shop-production
spec:
  minReadySeconds: 30
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: Parallel
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      dockflow.shawiizz.dev/service: ss-d
      dockflow.shawiizz.dev/stack: dockflow-shop-production
  serviceName: ss-d-hl
  template:
    metadata:
      annotations:
        dockflow.shawiizz.dev/compose-service: ss-d
        kubectl.kubernetes.io/default-container: ss-d
      labels:
        app.kubernetes.io/instance: dockflow-shop-production
        app.kubernetes.io/name: ss-d
        dockflow.shawiizz.dev/role: app
        dockflow.shawiizz.dev/service: ss-d
        dockflow.shawiizz.dev/stack: dockflow-shop-production
    spec:
      automountServiceAccountToken: false
      containers:
        - name: ss-d
          image: nginx:1.27
          imagePullPolicy: IfNotPresent
      enableServiceLinks: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 10
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              dockflow.shawiizz.dev/service: ss-d
              dockflow.shawiizz.dev/stack: dockflow-shop-production
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
  updateStrategy:
    type: RollingUpdate
