// Generated by cli/scripts/pin-kubernetes.ts; do not edit.
// Refresh from cli/: bun run scripts/pin-kubernetes.ts --k3s <version> --helm <version> --traefik-chart <version>

// Property map of the Middleware CRD shipped in the pinned Traefik chart, used to parse and coerce
// `traefik.http.middlewares.*` labels (design-04 2.14.1).

/** JSON-schema type of a CRD property; label values are coerced by it (design-04 2.14.1 rule 4). */
export type CrdPropertyType =
  | 'string'
  | 'integer'
  | 'number'
  | 'boolean'
  | 'int-or-string'
  | 'array'
  | 'object'
  /** x-kubernetes-preserve-unknown-fields: any content, nothing to validate */
  | 'any';

export interface CrdPropertyNode {
  /** property name as the CRD spells it; empty for array items and map values */
  readonly canonical: string;
  readonly type: CrdPropertyType;
  /** element schema of an array */
  readonly items?: CrdPropertyNode;
  /** value schema of a map, whose keys are chosen by the user and kept as written */
  readonly additionalProperties?: CrdPropertyNode;
  /** named properties of an object, keyed by lowercase name */
  readonly properties?: Readonly<Record<string, CrdPropertyNode>>;
}

/** The chart this map was extracted from; it must equal TRAEFIK_CHART_PIN. */
export const MIDDLEWARE_SCHEMA_SOURCE = {
  chart: 'traefik',
  chartVersion: '41.6.0',
  chartSha256: 'cd7254ea853da73bdb88edc896f079b88d43ffa0bfe699fdbf21081361eac365',
  appVersion: 'v3.7.13',
  file: 'traefik/crds/traefik.io_middlewares.yaml',
  apiVersion: 'traefik.io/v1alpha1',
} as const;

/** Middleware types (the properties of the CRD `spec`), keyed by lowercase name. */
export const MIDDLEWARE_SCHEMA: Readonly<Record<string, CrdPropertyNode>> = {
  addprefix: {
    canonical: 'addPrefix',
    type: 'object',
    properties: {
      prefix: { canonical: 'prefix', type: 'string' },
    },
  },
  basicauth: {
    canonical: 'basicAuth',
    type: 'object',
    properties: {
      headerfield: { canonical: 'headerField', type: 'string' },
      realm: { canonical: 'realm', type: 'string' },
      removeheader: { canonical: 'removeHeader', type: 'boolean' },
      secret: { canonical: 'secret', type: 'string' },
    },
  },
  buffering: {
    canonical: 'buffering',
    type: 'object',
    properties: {
      maxrequestbodybytes: { canonical: 'maxRequestBodyBytes', type: 'integer' },
      maxresponsebodybytes: { canonical: 'maxResponseBodyBytes', type: 'integer' },
      memrequestbodybytes: { canonical: 'memRequestBodyBytes', type: 'integer' },
      memresponsebodybytes: { canonical: 'memResponseBodyBytes', type: 'integer' },
      retryexpression: { canonical: 'retryExpression', type: 'string' },
    },
  },
  chain: {
    canonical: 'chain',
    type: 'object',
    properties: {
      middlewares: {
        canonical: 'middlewares',
        type: 'array',
        items: {
          canonical: '',
          type: 'object',
          properties: {
            name: { canonical: 'name', type: 'string' },
            namespace: { canonical: 'namespace', type: 'string' },
          },
        },
      },
    },
  },
  circuitbreaker: {
    canonical: 'circuitBreaker',
    type: 'object',
    properties: {
      checkperiod: { canonical: 'checkPeriod', type: 'int-or-string' },
      expression: { canonical: 'expression', type: 'string' },
      fallbackduration: { canonical: 'fallbackDuration', type: 'int-or-string' },
      recoveryduration: { canonical: 'recoveryDuration', type: 'int-or-string' },
      responsecode: { canonical: 'responseCode', type: 'integer' },
    },
  },
  compress: {
    canonical: 'compress',
    type: 'object',
    properties: {
      defaultencoding: { canonical: 'defaultEncoding', type: 'string' },
      encodings: { canonical: 'encodings', type: 'array', items: { canonical: '', type: 'string' } },
      excludedcontenttypes: { canonical: 'excludedContentTypes', type: 'array', items: { canonical: '', type: 'string' } },
      includedcontenttypes: { canonical: 'includedContentTypes', type: 'array', items: { canonical: '', type: 'string' } },
      minresponsebodybytes: { canonical: 'minResponseBodyBytes', type: 'integer' },
    },
  },
  contenttype: {
    canonical: 'contentType',
    type: 'object',
    properties: {
      autodetect: { canonical: 'autoDetect', type: 'boolean' },
    },
  },
  digestauth: {
    canonical: 'digestAuth',
    type: 'object',
    properties: {
      headerfield: { canonical: 'headerField', type: 'string' },
      realm: { canonical: 'realm', type: 'string' },
      removeheader: { canonical: 'removeHeader', type: 'boolean' },
      secret: { canonical: 'secret', type: 'string' },
    },
  },
  encodedcharacters: {
    canonical: 'encodedCharacters',
    type: 'object',
    properties: {
      allowencodedbackslash: { canonical: 'allowEncodedBackSlash', type: 'boolean' },
      allowencodedhash: { canonical: 'allowEncodedHash', type: 'boolean' },
      allowencodednullcharacter: { canonical: 'allowEncodedNullCharacter', type: 'boolean' },
      allowencodedpercent: { canonical: 'allowEncodedPercent', type: 'boolean' },
      allowencodedquestionmark: { canonical: 'allowEncodedQuestionMark', type: 'boolean' },
      allowencodedsemicolon: { canonical: 'allowEncodedSemicolon', type: 'boolean' },
      allowencodedslash: { canonical: 'allowEncodedSlash', type: 'boolean' },
    },
  },
  errors: {
    canonical: 'errors',
    type: 'object',
    properties: {
      errorrequestheaders: { canonical: 'errorRequestHeaders', type: 'array', items: { canonical: '', type: 'string' } },
      query: { canonical: 'query', type: 'string' },
      service: {
        canonical: 'service',
        type: 'object',
        properties: {
          healthcheck: {
            canonical: 'healthCheck',
            type: 'object',
            properties: {
              followredirects: { canonical: 'followRedirects', type: 'boolean' },
              headers: { canonical: 'headers', type: 'object', additionalProperties: { canonical: '', type: 'string' } },
              hostname: { canonical: 'hostname', type: 'string' },
              interval: { canonical: 'interval', type: 'int-or-string' },
              method: { canonical: 'method', type: 'string' },
              mode: { canonical: 'mode', type: 'string' },
              path: { canonical: 'path', type: 'string' },
              port: { canonical: 'port', type: 'integer' },
              scheme: { canonical: 'scheme', type: 'string' },
              status: { canonical: 'status', type: 'integer' },
              timeout: { canonical: 'timeout', type: 'int-or-string' },
              unhealthyinterval: { canonical: 'unhealthyInterval', type: 'int-or-string' },
            },
          },
          kind: { canonical: 'kind', type: 'string' },
          middlewares: {
            canonical: 'middlewares',
            type: 'array',
            items: {
              canonical: '',
              type: 'object',
              properties: {
                name: { canonical: 'name', type: 'string' },
                namespace: { canonical: 'namespace', type: 'string' },
              },
            },
          },
          name: { canonical: 'name', type: 'string' },
          namespace: { canonical: 'namespace', type: 'string' },
          nativelb: { canonical: 'nativeLB', type: 'boolean' },
          nodeportlb: { canonical: 'nodePortLB', type: 'boolean' },
          passhostheader: { canonical: 'passHostHeader', type: 'boolean' },
          passivehealthcheck: {
            canonical: 'passiveHealthCheck',
            type: 'object',
            properties: {
              failurewindow: { canonical: 'failureWindow', type: 'int-or-string' },
              maxfailedattempts: { canonical: 'maxFailedAttempts', type: 'integer' },
            },
          },
          port: { canonical: 'port', type: 'int-or-string' },
          responseforwarding: {
            canonical: 'responseForwarding',
            type: 'object',
            properties: {
              flushinterval: { canonical: 'flushInterval', type: 'string' },
            },
          },
          scheme: { canonical: 'scheme', type: 'string' },
          serverstransport: { canonical: 'serversTransport', type: 'string' },
          sticky: {
            canonical: 'sticky',
            type: 'object',
            properties: {
              cookie: {
                canonical: 'cookie',
                type: 'object',
                properties: {
                  domain: { canonical: 'domain', type: 'string' },
                  httponly: { canonical: 'httpOnly', type: 'boolean' },
                  maxage: { canonical: 'maxAge', type: 'integer' },
                  name: { canonical: 'name', type: 'string' },
                  path: { canonical: 'path', type: 'string' },
                  samesite: { canonical: 'sameSite', type: 'string' },
                  secure: { canonical: 'secure', type: 'boolean' },
                },
              },
            },
          },
          strategy: { canonical: 'strategy', type: 'string' },
          weight: { canonical: 'weight', type: 'integer' },
        },
      },
      status: { canonical: 'status', type: 'array', items: { canonical: '', type: 'string' } },
      statusrewrites: { canonical: 'statusRewrites', type: 'object', additionalProperties: { canonical: '', type: 'integer' } },
    },
  },
  forwardauth: {
    canonical: 'forwardAuth',
    type: 'object',
    properties: {
      addauthcookiestoresponse: { canonical: 'addAuthCookiesToResponse', type: 'array', items: { canonical: '', type: 'string' } },
      address: { canonical: 'address', type: 'string' },
      authrequestheaders: { canonical: 'authRequestHeaders', type: 'array', items: { canonical: '', type: 'string' } },
      authresponseheaders: { canonical: 'authResponseHeaders', type: 'array', items: { canonical: '', type: 'string' } },
      authresponseheadersregex: { canonical: 'authResponseHeadersRegex', type: 'string' },
      authsigninurl: { canonical: 'authSigninURL', type: 'string' },
      forwardbody: { canonical: 'forwardBody', type: 'boolean' },
      headerfield: { canonical: 'headerField', type: 'string' },
      maxbodysize: { canonical: 'maxBodySize', type: 'integer' },
      maxresponsebodysize: { canonical: 'maxResponseBodySize', type: 'integer' },
      preservelocationheader: { canonical: 'preserveLocationHeader', type: 'boolean' },
      preserverequestmethod: { canonical: 'preserveRequestMethod', type: 'boolean' },
      tls: {
        canonical: 'tls',
        type: 'object',
        properties: {
          caoptional: { canonical: 'caOptional', type: 'boolean' },
          casecret: { canonical: 'caSecret', type: 'string' },
          certsecret: { canonical: 'certSecret', type: 'string' },
          insecureskipverify: { canonical: 'insecureSkipVerify', type: 'boolean' },
        },
      },
      trustforwardheader: { canonical: 'trustForwardHeader', type: 'boolean' },
    },
  },
  grpcweb: {
    canonical: 'grpcWeb',
    type: 'object',
    properties: {
      alloworigins: { canonical: 'allowOrigins', type: 'array', items: { canonical: '', type: 'string' } },
    },
  },
  headers: {
    canonical: 'headers',
    type: 'object',
    properties: {
      accesscontrolallowcredentials: { canonical: 'accessControlAllowCredentials', type: 'boolean' },
      accesscontrolallowheaders: { canonical: 'accessControlAllowHeaders', type: 'array', items: { canonical: '', type: 'string' } },
      accesscontrolallowmethods: { canonical: 'accessControlAllowMethods', type: 'array', items: { canonical: '', type: 'string' } },
      accesscontrolalloworiginlist: { canonical: 'accessControlAllowOriginList', type: 'array', items: { canonical: '', type: 'string' } },
      accesscontrolalloworiginlistregex: { canonical: 'accessControlAllowOriginListRegex', type: 'array', items: { canonical: '', type: 'string' } },
      accesscontrolexposeheaders: { canonical: 'accessControlExposeHeaders', type: 'array', items: { canonical: '', type: 'string' } },
      accesscontrolmaxage: { canonical: 'accessControlMaxAge', type: 'integer' },
      addvaryheader: { canonical: 'addVaryHeader', type: 'boolean' },
      allowedhosts: { canonical: 'allowedHosts', type: 'array', items: { canonical: '', type: 'string' } },
      browserxssfilter: { canonical: 'browserXssFilter', type: 'boolean' },
      contentsecuritypolicy: { canonical: 'contentSecurityPolicy', type: 'string' },
      contentsecuritypolicyreportonly: { canonical: 'contentSecurityPolicyReportOnly', type: 'string' },
      contenttypenosniff: { canonical: 'contentTypeNosniff', type: 'boolean' },
      custombrowserxssvalue: { canonical: 'customBrowserXSSValue', type: 'string' },
      customframeoptionsvalue: { canonical: 'customFrameOptionsValue', type: 'string' },
      customrequestheaders: { canonical: 'customRequestHeaders', type: 'object', additionalProperties: { canonical: '', type: 'string' } },
      customresponseheaders: { canonical: 'customResponseHeaders', type: 'object', additionalProperties: { canonical: '', type: 'string' } },
      featurepolicy: { canonical: 'featurePolicy', type: 'string' },
      forcestsheader: { canonical: 'forceSTSHeader', type: 'boolean' },
      framedeny: { canonical: 'frameDeny', type: 'boolean' },
      hostsproxyheaders: { canonical: 'hostsProxyHeaders', type: 'array', items: { canonical: '', type: 'string' } },
      isdevelopment: { canonical: 'isDevelopment', type: 'boolean' },
      permissionspolicy: { canonical: 'permissionsPolicy', type: 'string' },
      publickey: { canonical: 'publicKey', type: 'string' },
      referrerpolicy: { canonical: 'referrerPolicy', type: 'string' },
      sslforcehost: { canonical: 'sslForceHost', type: 'boolean' },
      sslhost: { canonical: 'sslHost', type: 'string' },
      sslproxyheaders: { canonical: 'sslProxyHeaders', type: 'object', additionalProperties: { canonical: '', type: 'string' } },
      sslredirect: { canonical: 'sslRedirect', type: 'boolean' },
      ssltemporaryredirect: { canonical: 'sslTemporaryRedirect', type: 'boolean' },
      stsincludesubdomains: { canonical: 'stsIncludeSubdomains', type: 'boolean' },
      stspreload: { canonical: 'stsPreload', type: 'boolean' },
      stsseconds: { canonical: 'stsSeconds', type: 'integer' },
    },
  },
  inflightreq: {
    canonical: 'inFlightReq',
    type: 'object',
    properties: {
      amount: { canonical: 'amount', type: 'integer' },
      sourcecriterion: {
        canonical: 'sourceCriterion',
        type: 'object',
        properties: {
          ipstrategy: {
            canonical: 'ipStrategy',
            type: 'object',
            properties: {
              depth: { canonical: 'depth', type: 'integer' },
              excludedips: { canonical: 'excludedIPs', type: 'array', items: { canonical: '', type: 'string' } },
              ipv6subnet: { canonical: 'ipv6Subnet', type: 'integer' },
            },
          },
          requestheadername: { canonical: 'requestHeaderName', type: 'string' },
          requesthost: { canonical: 'requestHost', type: 'boolean' },
        },
      },
    },
  },
  ipallowlist: {
    canonical: 'ipAllowList',
    type: 'object',
    properties: {
      ipstrategy: {
        canonical: 'ipStrategy',
        type: 'object',
        properties: {
          depth: { canonical: 'depth', type: 'integer' },
          excludedips: { canonical: 'excludedIPs', type: 'array', items: { canonical: '', type: 'string' } },
          ipv6subnet: { canonical: 'ipv6Subnet', type: 'integer' },
        },
      },
      rejectstatuscode: { canonical: 'rejectStatusCode', type: 'integer' },
      sourcerange: { canonical: 'sourceRange', type: 'array', items: { canonical: '', type: 'string' } },
    },
  },
  ipwhitelist: {
    canonical: 'ipWhiteList',
    type: 'object',
    properties: {
      ipstrategy: {
        canonical: 'ipStrategy',
        type: 'object',
        properties: {
          depth: { canonical: 'depth', type: 'integer' },
          excludedips: { canonical: 'excludedIPs', type: 'array', items: { canonical: '', type: 'string' } },
          ipv6subnet: { canonical: 'ipv6Subnet', type: 'integer' },
        },
      },
      sourcerange: { canonical: 'sourceRange', type: 'array', items: { canonical: '', type: 'string' } },
    },
  },
  passtlsclientcert: {
    canonical: 'passTLSClientCert',
    type: 'object',
    properties: {
      info: {
        canonical: 'info',
        type: 'object',
        properties: {
          issuer: {
            canonical: 'issuer',
            type: 'object',
            properties: {
              commonname: { canonical: 'commonName', type: 'boolean' },
              country: { canonical: 'country', type: 'boolean' },
              domaincomponent: { canonical: 'domainComponent', type: 'boolean' },
              locality: { canonical: 'locality', type: 'boolean' },
              organization: { canonical: 'organization', type: 'boolean' },
              province: { canonical: 'province', type: 'boolean' },
              serialnumber: { canonical: 'serialNumber', type: 'boolean' },
            },
          },
          notafter: { canonical: 'notAfter', type: 'boolean' },
          notbefore: { canonical: 'notBefore', type: 'boolean' },
          sans: { canonical: 'sans', type: 'boolean' },
          serialnumber: { canonical: 'serialNumber', type: 'boolean' },
          subject: {
            canonical: 'subject',
            type: 'object',
            properties: {
              commonname: { canonical: 'commonName', type: 'boolean' },
              country: { canonical: 'country', type: 'boolean' },
              domaincomponent: { canonical: 'domainComponent', type: 'boolean' },
              locality: { canonical: 'locality', type: 'boolean' },
              organization: { canonical: 'organization', type: 'boolean' },
              organizationalunit: { canonical: 'organizationalUnit', type: 'boolean' },
              province: { canonical: 'province', type: 'boolean' },
              serialnumber: { canonical: 'serialNumber', type: 'boolean' },
            },
          },
        },
      },
      pem: { canonical: 'pem', type: 'boolean' },
    },
  },
  plugin: { canonical: 'plugin', type: 'object', additionalProperties: { canonical: '', type: 'any' } },
  ratelimit: {
    canonical: 'rateLimit',
    type: 'object',
    properties: {
      average: { canonical: 'average', type: 'integer' },
      burst: { canonical: 'burst', type: 'integer' },
      period: { canonical: 'period', type: 'int-or-string' },
      redis: {
        canonical: 'redis',
        type: 'object',
        properties: {
          db: { canonical: 'db', type: 'integer' },
          dialtimeout: { canonical: 'dialTimeout', type: 'int-or-string' },
          endpoints: { canonical: 'endpoints', type: 'array', items: { canonical: '', type: 'string' } },
          maxactiveconns: { canonical: 'maxActiveConns', type: 'integer' },
          minidleconns: { canonical: 'minIdleConns', type: 'integer' },
          poolsize: { canonical: 'poolSize', type: 'integer' },
          readtimeout: { canonical: 'readTimeout', type: 'int-or-string' },
          secret: { canonical: 'secret', type: 'string' },
          tls: {
            canonical: 'tls',
            type: 'object',
            properties: {
              casecret: { canonical: 'caSecret', type: 'string' },
              certsecret: { canonical: 'certSecret', type: 'string' },
              insecureskipverify: { canonical: 'insecureSkipVerify', type: 'boolean' },
            },
          },
          writetimeout: { canonical: 'writeTimeout', type: 'int-or-string' },
        },
      },
      sourcecriterion: {
        canonical: 'sourceCriterion',
        type: 'object',
        properties: {
          ipstrategy: {
            canonical: 'ipStrategy',
            type: 'object',
            properties: {
              depth: { canonical: 'depth', type: 'integer' },
              excludedips: { canonical: 'excludedIPs', type: 'array', items: { canonical: '', type: 'string' } },
              ipv6subnet: { canonical: 'ipv6Subnet', type: 'integer' },
            },
          },
          requestheadername: { canonical: 'requestHeaderName', type: 'string' },
          requesthost: { canonical: 'requestHost', type: 'boolean' },
        },
      },
    },
  },
  redirectregex: {
    canonical: 'redirectRegex',
    type: 'object',
    properties: {
      permanent: { canonical: 'permanent', type: 'boolean' },
      regex: { canonical: 'regex', type: 'string' },
      replacement: { canonical: 'replacement', type: 'string' },
    },
  },
  redirectscheme: {
    canonical: 'redirectScheme',
    type: 'object',
    properties: {
      permanent: { canonical: 'permanent', type: 'boolean' },
      port: { canonical: 'port', type: 'string' },
      scheme: { canonical: 'scheme', type: 'string' },
    },
  },
  replacepath: {
    canonical: 'replacePath',
    type: 'object',
    properties: {
      path: { canonical: 'path', type: 'string' },
    },
  },
  replacepathregex: {
    canonical: 'replacePathRegex',
    type: 'object',
    properties: {
      regex: { canonical: 'regex', type: 'string' },
      replacement: { canonical: 'replacement', type: 'string' },
    },
  },
  retry: {
    canonical: 'retry',
    type: 'object',
    properties: {
      attempts: { canonical: 'attempts', type: 'integer' },
      disableretryonnetworkerror: { canonical: 'disableRetryOnNetworkError', type: 'boolean' },
      initialinterval: { canonical: 'initialInterval', type: 'int-or-string' },
      maxrequestbodybytes: { canonical: 'maxRequestBodyBytes', type: 'integer' },
      retrynonidempotentmethod: { canonical: 'retryNonIdempotentMethod', type: 'boolean' },
      status: { canonical: 'status', type: 'array', items: { canonical: '', type: 'string' } },
      timeout: { canonical: 'timeout', type: 'int-or-string' },
    },
  },
  stripprefix: {
    canonical: 'stripPrefix',
    type: 'object',
    properties: {
      forceslash: { canonical: 'forceSlash', type: 'boolean' },
      prefixes: { canonical: 'prefixes', type: 'array', items: { canonical: '', type: 'string' } },
    },
  },
  stripprefixregex: {
    canonical: 'stripPrefixRegex',
    type: 'object',
    properties: {
      regex: { canonical: 'regex', type: 'array', items: { canonical: '', type: 'string' } },
    },
  },
};
