// Generated by cli/scripts/pin-kubernetes.ts; do not edit.
// Refresh from cli/: bun run scripts/pin-kubernetes.ts --k3s <version> --helm <version> --traefik-chart <version>

/** A download fetched over HTTPS and verified against its sha256 before use (DESIGN-CORE 8.7). */
export interface PinnedDownload {
  readonly url: string;
  readonly sha256: string;
}

export const PINNED_ARCHES = ['amd64', 'arm64'] as const;
export type PinnedArch = (typeof PINNED_ARCHES)[number];

export interface HelmPin {
  readonly version: string;
  readonly archives: Readonly<Record<PinnedArch, PinnedDownload>>;
}

export interface TraefikChartPin {
  readonly chart: string;
  readonly repo: string;
  readonly version: string;
  /** the chart archive, as the repository index lists it */
  readonly url: string;
  /** sha256 of the chart archive (equals the repository index digest) */
  readonly sha256: string;
  readonly appVersion: string;
  /** index digest of docker.io/traefik:<appVersion>; the tag is mutable, the digest is not */
  readonly imageDigest?: string;
}

export const HELM_PIN = {
  version: 'v4.3.0',
  archives: {
    amd64: {
      url: 'https://get.helm.sh/helm-v4.3.0-linux-amd64.tar.gz',
      sha256: '86584a54def73570558f66f5111cc53dfed56689637ae32c1201205d494f54fb',
    },
    arm64: {
      url: 'https://get.helm.sh/helm-v4.3.0-linux-arm64.tar.gz',
      sha256: '31c5794dd55c66a51e6b7d2e2ac7a114ae8b1de41ff1d9ba51748ac973b06a08',
    },
  },
} as const satisfies HelmPin;

// Typed rather than `as const` so a caller can pass a pin without an image digest.
export const TRAEFIK_CHART_PIN: TraefikChartPin = {
  chart: 'traefik',
  repo: 'https://traefik.github.io/charts',
  version: '41.6.0',
  url: 'https://traefik.github.io/charts/traefik/traefik-41.6.0.tgz',
  /** sha256 of traefik-41.6.0.tgz (equals the repository index digest) */
  sha256: 'cd7254ea853da73bdb88edc896f079b88d43ffa0bfe699fdbf21081361eac365',
  appVersion: 'v3.7.13',
  imageDigest: 'sha256:f86a2cab1b5c649070c49f883c743dd32d8485a56e3368c5f93b9e91f1e91259',
};
