#!/usr/bin/env bun
/**
 * Builds a Linux Dockflow binary pinned to the previous k3s minor (E-74, `setup-upgrade`): that
 * binary provisions an old cluster, then the binary under test upgrades it with `--upgrade`.
 *
 * Never edits the real `k3s/versions.ts` (owned by another package): `cli/` is copied into a
 * throwaway build directory under `.cache/previous-pin-src`, only the COPY's `k3s/versions.ts` is
 * rewritten with the previous pin, and only that copy is built. The real source tree is never
 * touched, even transiently — the same principle fixtures.ts uses for test fixtures.
 *
 * Usage: bun run testing/e2e/k3s/tools/build-previous-pin-cli.ts [--pin <file>]
 * `--pin` points at a previous-pin JSON (shape of `tools/prepare-downloads.ts`'s `PreviousPin`,
 * e.g. `.cache/downloads/previous-pin.json` written by `prepare-downloads.ts --previous-pin`).
 * Without it, the previous minor is resolved the same way `prepare-downloads.ts` does.
 */

import { cpSync, existsSync, mkdirSync, rmSync, writeFileSync } from "fs";
import { join } from "path";
import { previousPin, type PreviousPin } from "./prepare-downloads";
import { CACHE_DIR, exec } from "../../helpers/cluster";

const E2E_DIR = join(import.meta.dir, "..", "..");
const REPO_ROOT = join(E2E_DIR, "..", "..");
const REAL_CLI_DIR = join(REPO_ROOT, "cli");
const BUILD_ROOT = join(CACHE_DIR, "previous-pin-src");
const OUT_DIR = join(CACHE_DIR, "previous-pin");

function log(message: string): void {
  process.stdout.write(`${message}\n`);
}

/** The exact shape of the exported `K3S_PIN` object (versions.ts), with the previous-minor values. */
function versionsFileContent(pin: PreviousPin): string {
  return `// Generated by testing/e2e/k3s/tools/build-previous-pin-cli.ts for a throwaway build only —
// never written into the real cli/ tree. Shape matches the real k3s/versions.ts (pin-kubernetes.ts).

import type { PinnedArch, PinnedDownload } from '../versions';

export type { PinnedDownload } from '../versions';

export interface K3sPin {
  readonly version: string;
  readonly minimumServerVersion: string;
  readonly installScript: PinnedDownload;
  readonly binaries: Readonly<Record<PinnedArch, PinnedDownload>>;
}

export const K3S_PIN = ${JSON.stringify({ version: pin.version, minimumServerVersion: pin.version, installScript: pin.installScript, binaries: pin.binaries }, null, 2)} as const satisfies K3sPin;
`;
}

/**
 * Copies `cli/` into a throwaway build directory (everything except `node_modules` and `dist`, which
 * are reinstalled/rebuilt there), so the real source tree is never written to.
 */
function copyCliSource(): void {
  rmSync(BUILD_ROOT, { recursive: true, force: true });
  mkdirSync(BUILD_ROOT, { recursive: true });
  cpSync(REAL_CLI_DIR, BUILD_ROOT, {
    recursive: true,
    filter: (src) => {
      const base = src.slice(REAL_CLI_DIR.length + 1).split(/[\\/]/)[0];
      return base !== "node_modules" && base !== "dist";
    },
  });
}

export interface BuildPreviousPinCliOptions {
  /** a previous-pin JSON file (PreviousPin shape); resolved online when omitted */
  pinFile?: string;
}

/** Builds the previous-pin Linux binary, returns its path. */
export async function buildPreviousPinCli(opts: BuildPreviousPinCliOptions = {}): Promise<string> {
  const pin = await previousPin(opts.pinFile ?? true);
  log(`[build-previous-pin-cli] previous pin resolved: k3s ${pin.version}`);

  copyCliSource();
  const versionsPath = join(BUILD_ROOT, "src", "services", "orchestrator", "kubernetes", "k3s", "versions.ts");
  if (!existsSync(versionsPath)) throw new Error(`${versionsPath} does not exist in the copied cli/ tree`);
  writeFileSync(versionsPath, versionsFileContent(pin));

  log("[build-previous-pin-cli] bun install...");
  await exec(["bun", "install", "--frozen-lockfile"], { cwd: BUILD_ROOT, timeoutMs: 180_000 });
  log("[build-previous-pin-cli] building linux-x64...");
  await exec(["bun", "run", "build", "linux-x64"], { cwd: BUILD_ROOT, timeoutMs: 180_000 });

  const built = join(BUILD_ROOT, "dist", "dockflow-linux-x64");
  if (!existsSync(built)) throw new Error(`Build did not produce ${built}`);
  mkdirSync(OUT_DIR, { recursive: true });
  const out = join(OUT_DIR, "dockflow-linux-x64");
  rmSync(out, { force: true });
  cpSync(built, out);
  log(`[build-previous-pin-cli] previous-pin binary (k3s ${pin.version}): ${out}`);
  return out;
}

const USAGE = "Usage: bun run testing/e2e/k3s/tools/build-previous-pin-cli.ts [--pin <file>]";

function parseArgs(argv: string[]): BuildPreviousPinCliOptions {
  const opts: BuildPreviousPinCliOptions = {};
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === "--pin") opts.pinFile = argv[++i];
    else throw new Error(`Unknown argument ${argv[i]}\n${USAGE}`);
  }
  return opts;
}

if (import.meta.main) {
  try {
    await buildPreviousPinCli(parseArgs(process.argv.slice(2)));
  } catch (error) {
    process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
    process.exit(1);
  }
}
