// Generated by cli/scripts/pin-kubernetes.ts; do not edit.
// Refresh from cli/: bun run scripts/pin-kubernetes.ts --k3s <version> --helm <version> --traefik-chart <version>

import type { PinnedArch, PinnedDownload } from '../versions';

export type { PinnedDownload } from '../versions';

export interface K3sPin {
  readonly version: string;
  /** oldest server version this release deploys to (preflight) and upgrades from */
  readonly minimumServerVersion: string;
  readonly installScript: PinnedDownload;
  readonly binaries: Readonly<Record<PinnedArch, PinnedDownload>>;
}

export const K3S_PIN = {
  version: 'v1.36.4+k3s1',
  /** oldest server version this release deploys to (preflight) and upgrades from */
  minimumServerVersion: 'v1.34.0',
  installScript: {
    url: 'https://raw.githubusercontent.com/k3s-io/k3s/v1.36.4%2Bk3s1/install.sh',
    sha256: '46177d4c99440b4c0311b67233823a8e8a2fc09693f6c89af1a7161e152fbfad',
  },
  binaries: {
    amd64: {
      url: 'https://github.com/k3s-io/k3s/releases/download/v1.36.4%2Bk3s1/k3s',
      sha256: '835873f37245fc615f547a2fe2af9402a347875f13fa64a1f136de644955ea3f',
    },
    arm64: {
      url: 'https://github.com/k3s-io/k3s/releases/download/v1.36.4%2Bk3s1/k3s-arm64',
      sha256: 'c920706346d5ad4e5cd3c7bf1bb09ce71ebe07fec829e513e40f1caf98aed8bb',
    },
  },
} as const satisfies K3sPin;
