include:
  - remote: 'https://raw.githubusercontent.com/Shawiizz/dockflow/refs/tags/2.0.3/.gitlab/common/variables.yml'

stages:
  - build

build:
  stage: build
  image: ubuntu:22.04
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKFLOW_REPOSITORY_URL: https://github.com/Shawiizz/dockflow.git
    DOCKFLOW_FRAMEWORK_VERSION: 2.0.3
  before_script:
    - apt-get update && apt-get install -y git python3-pip ansible npm
    - npm i -g shawiizz-decomposerize
    - pip3 install pyyaml
  script:
    - |
      # Install Dockflow CLI (versionnée)
      curl -fsSL https://raw.githubusercontent.com/Shawiizz/dockflow/2.0.3/install.sh | bash
      # Build images avec Dockflow CLI
      dockflow build "$CI_COMMIT_REF_NAME"
  rules:
    - if: '$CI_COMMIT_TAG'
      when: never
    - when: always
