include:
  - remote: 'https://raw.githubusercontent.com/Shawiizz/devops-framework/refs/tags/1.0.37-dev4/.gitlab/common/steps.yml'
  - remote: 'https://raw.githubusercontent.com/Shawiizz/devops-framework/refs/tags/1.0.37-dev4/.gitlab/common/variables.yml'

stages:
  - build

build:
  stage: build
  extends:
    - .common-variables
    - .build-docker-images
  before_script:
    - export ENV=build
    - export VERSION=build
  rules:
    - if: '$CI_COMMIT_TAG'
      when: never
    - when: always
