include:
  - remote: 'https://raw.githubusercontent.com/Shawiizz/dockflow/refs/tags/1.0.53/.gitlab/common/variables.yml'

stages:
  - build

build:
  stage: build
  extends:
    - .common-variables
  before_script:
    - export ENV=build
    - export VERSION=build
    - export ROOT_PATH=$(pwd)
    - git clone --branch "$DOCKFLOW_FRAMEWORK_VERSION" "$DOCKFLOW_REPOSITORY_URL" dockflow
  script:
    - |
      source dockflow/.common/scripts/load_env.sh "$ENV"
      
      # Run Ansible playbook to build images
      cd dockflow
      ansible-playbook ansible/playbooks/build_images.yml --connection=local
  rules:
    - if: '$CI_COMMIT_TAG'
      when: never
    - when: always
