include:
  - remote: 'https://raw.githubusercontent.com/Shawiizz/dockflow/refs/tags/2.0.0-dev7/.gitlab/common/variables.yml'

stages:
  - build

build:
  stage: build
  image: ubuntu:22.04
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKFLOW_REPOSITORY_URL: https://github.com/Shawiizz/dockflow.git
    DOCKFLOW_FRAMEWORK_VERSION: 2.0.0-dev7
  before_script:
    - apt-get update && apt-get install -y git python3-pip ansible npm
    - npm i -g shawiizz-decomposerize
    - pip3 install pyyaml
    - git clone --branch "$DOCKFLOW_FRAMEWORK_VERSION" "$DOCKFLOW_REPOSITORY_URL" /tmp/dockflow
  script:
    - |
      export ROOT_PATH=$(pwd)
      cd /tmp/dockflow
      ansible-playbook ansible/playbooks/build_images.yml --connection=local
  rules:
    - if: '$CI_COMMIT_TAG'
      when: never
    - when: always
