include:
  - remote: 'https://raw.githubusercontent.com/Shawiizz/dockflow/refs/tags/2.0.0-dev6/.gitlab/common/steps.yml'
  - remote: 'https://raw.githubusercontent.com/Shawiizz/dockflow/refs/tags/2.0.0-dev6/.gitlab/common/variables.yml'

stages:
  - deploy

deploy:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_TAG'
  extends:
    - .common-variables
    - .prepare-env
    - .deploy-with-dockflow
