include:
  - remote: 'https://raw.githubusercontent.com/Shawiizz/devops-framework/refs/tags/1.0.33-dev2/.gitlab/common/steps.yml'
  - remote: 'https://raw.githubusercontent.com/Shawiizz/devops-framework/refs/tags/1.0.33-dev2/.gitlab/common/variables.yml'

stages:
  - deploy

deploy-branch:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH'
  extends:
    - .common-variables
    - .prepare-env
    - .build-docker-images
    - .deploy-with-ansible
