include:
  - remote: 'https://raw.githubusercontent.com/Shawiizz/devops/refs/tags/1.0.14/.gitlab/ci-templates/build-steps.yml'

stages:
  - deploy
  - deploy-build

.common-deploy:
  image: shawiizz/devops-ci:1.0.3
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DEVOPS_REPOSITORY_URL: https://github.com/Shawiizz/devops.git
    DEVOPS_FRAMEWORK_VERSION: 1.0.14
  before_script:
    - |
      TAG=$CI_COMMIT_REF_NAME
      ENVIRONMENT="production"
  
      if [[ "$TAG" == *"-"* ]]; then
        ENVIRONMENT="${TAG##*-}"
      fi
      
      export ENV=$ENVIRONMENT
      export VERSION=$TAG
      
      if [ ! -f "deployment/env/.env.${ENV}" ]; then
          echo "File deployment/env/.env.${ENV} does not exist, cannot execute on unknown environment"
          exit 1
      fi
      
      while IFS= read -r line || [[ -n "$line" ]]; do
        [[ "$line" =~ ^[[:space:]]*#.*$ || -z "$line" ]] && continue
        [[ "$line" =~ ^[A-Za-z_][A-Za-z0-9_]*= ]] && export "$line"
      done < <(cat "deployment/env/.env.${ENV}"; echo)

deploy:build:
  stage: deploy-build
  rules:
    - if: '$CI_COMMIT_TAG'
  extends:
    - .common-deploy
    - .build-docker
  artifacts:
    paths:
      - deployment/docker/*.tar
    expire_in: 1 day

deploy:
  stage: deploy
  needs: ["deploy:build"]
  extends:
      - .common-deploy
  rules:
    - if: '$CI_COMMIT_TAG'
  script:
    - |
      git clone --branch "$DEVOPS_FRAMEWORK_VERSION" "$DEVOPS_REPOSITORY_URL" ansible

      mkdir -p ./docker_images
      cp deployment/docker/*.tar ./docker_images/
      
      mkdir -p ansible/ssh
      echo "$(printenv "$(echo "${ENV}" | tr '[:lower:]' '[:upper:]')_SSH_PRIVATE_KEY")" | tr -d '\r' > ansible/ssh/main_private_key
      chmod 600 ansible/ssh/*
      
      eval "$(ssh-agent -s)"
      ssh-add ansible/ssh/main_private_key      
      
      cd ansible
      export ANSIBLE_HOST_KEY_CHECKING=False
      export ANSIBLE_BECOME_PASSWORD=$ANSIBLE_BECOME_PASSWORD

      SKIP_TAGS="configure_host"
      if [ ! -d "../deployment/templates/nginx" ] || [ -z "$(ls -A ../deployment/templates/nginx 2>/dev/null)" ]; then
        echo "No nginx configuration found, skipping nginx role"
        SKIP_TAGS="${SKIP_TAGS},nginx"
      fi

      ansible-galaxy role install geerlingguy.docker
      ansible-playbook ansible/deploy.yml -i "$HOST," --user="$ANSIBLE_USER" --private-key=ansible/ssh/main_private_key --skip-tags "$SKIP_TAGS"
