#!/bin/bash
# Dockflow CLI Wrapper - One-line installer
# Usage: curl -fsSL https://raw.githubusercontent.com/Shawiizz/dockflow/main/cli/cli_wrapper.sh?$(date +%s) | bash
# Usage with specific branch: curl -fsSL https://raw.githubusercontent.com/Shawiizz/dockflow/main/cli/cli_wrapper.sh?$(date +%s) | BRANCH=develop bash
# The ?$(date +%s) adds a timestamp to bypass GitHub's CDN cache
#
# After installation, you can run 'dockflow' from anywhere!

# Branch to use (default: main)
BRANCH="${BRANCH:-main}"

# Installation directory
INSTALL_DIR="${DOCKFLOW_HOME:-$HOME/.dockflow}"
BIN_DIR="/usr/local/bin"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${CYAN}                     Dockflow CLI Installer                        ${NC}"
echo -e "${CYAN}                         Branch: $BRANCH                           ${NC}"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# Function to check if a command exists
command_exists() {
	command -v "$1" >/dev/null 2>&1
}

# Function to install package
install_package() {
	local package="$1"
	echo -e "${YELLOW}Installing $package...${NC}"

	if command_exists apt-get; then
		sudo apt-get update -qq
		sudo apt-get install -y "$package"
	elif command_exists yum; then
		sudo yum install -y "$package"
	elif command_exists dnf; then
		sudo dnf install -y "$package"
	elif command_exists pacman; then
		sudo pacman -S --noconfirm "$package"
	else
		echo -e "${RED}Error: Could not detect package manager${NC}"
		echo -e "${YELLOW}Please install $package manually${NC}"
		exit 1
	fi
}

echo -e "${BLUE}[1/5] Checking required dependencies...${NC}"

# Check and install required tools
MISSING_DEPS=()

if ! command_exists curl; then
	MISSING_DEPS+=("curl")
fi

if ! command_exists unzip; then
	MISSING_DEPS+=("unzip")
fi

if ! command_exists ansible; then
	MISSING_DEPS+=("ansible")
fi

if ! command_exists jq; then
	MISSING_DEPS+=("jq")
fi

if ! command_exists sshpass; then
	MISSING_DEPS+=("sshpass")
fi

if [ ${#MISSING_DEPS[@]} -gt 0 ]; then
	echo -e "${YELLOW}Missing dependencies detected: ${MISSING_DEPS[*]}${NC}"
	echo -e "${YELLOW}Installing missing dependencies...${NC}"

	for dep in "${MISSING_DEPS[@]}"; do
		install_package "$dep"
	done

	echo -e "${GREEN}✓ All dependencies installed${NC}"
else
	echo -e "${GREEN}✓ All dependencies are already installed${NC}"
fi

# Check Python version
echo -e "${BLUE}[2/5] Checking Python version...${NC}"
if command_exists python3; then
	PYTHON_VERSION=$(python3 --version 2>&1 | awk '{print $2}')
	echo -e "${GREEN}✓ Python $PYTHON_VERSION detected${NC}"
else
	echo -e "${RED}Error: Python 3 is required but not found${NC}"
	install_package "python3"
fi

# Check Ansible version
echo -e "${BLUE}[3/5] Checking Ansible version...${NC}"
ANSIBLE_VERSION=$(ansible --version 2>&1 | head -n1 | awk '{print $2}')
echo -e "${GREEN}✓ Ansible $ANSIBLE_VERSION detected${NC}"

# Create installation directory
echo -e "${BLUE}[4/6] Downloading Dockflow CLI...${NC}"

# Clean previous installation if exists
if [ -d "$INSTALL_DIR" ]; then
	echo -e "${YELLOW}Removing previous installation...${NC}"
	rm -rf "$INSTALL_DIR"
fi

mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR" || exit 1

# Download repository archive
ARCHIVE_URL="https://github.com/Shawiizz/dockflow/archive/refs/heads/${BRANCH}.zip"
echo -e "${YELLOW}Downloading repository archive from ${BRANCH} branch...${NC}"

if ! curl -fsSL -o dockflow.zip "$ARCHIVE_URL"; then
	echo -e "${RED}Error: Failed to download repository archive${NC}"
	echo -e "${YELLOW}Please check that the branch '${BRANCH}' exists${NC}"
	exit 1
fi

# Extract archive
echo -e "${YELLOW}Extracting files...${NC}"
unzip -q dockflow.zip
rm dockflow.zip

# Find extracted directory (format: dockflow-<branch>)
EXTRACTED_DIR=$(find . -maxdepth 1 -type d -name "dockflow-*" | head -n 1)

if [ -z "$EXTRACTED_DIR" ]; then
	echo -e "${RED}Error: Could not find extracted directory${NC}"
	exit 1
fi

# Move contents to installation directory
mv "$EXTRACTED_DIR"/* .
rm -rf "$EXTRACTED_DIR"

echo -e "${GREEN}✓ Dockflow CLI downloaded to $INSTALL_DIR${NC}"

# Make CLI executable
chmod +x "$INSTALL_DIR/cli/cli.sh"

# Create the dockflow command
echo -e "${BLUE}[5/6] Installing 'dockflow' command...${NC}"

# Create the launcher script
LAUNCHER_SCRIPT="$INSTALL_DIR/dockflow"
cat >"$LAUNCHER_SCRIPT" <<'LAUNCHER_EOF'
#!/bin/bash
# Dockflow CLI Launcher
# This script is auto-generated by the Dockflow installer

DOCKFLOW_HOME="${DOCKFLOW_HOME:-$HOME/.dockflow}"

if [ ! -d "$DOCKFLOW_HOME" ]; then
    echo "Error: Dockflow is not installed. Please run the installer:"
    echo "  curl -fsSL \"https://raw.githubusercontent.com/Shawiizz/dockflow/main/cli/cli_wrapper.sh?\$(date +%s)\" | bash"
    exit 1
fi

# Save the current working directory to pass to the CLI
export DOCKFLOW_WORKING_DIR="$(pwd)"

cd "$DOCKFLOW_HOME" || exit 1
exec bash -c "./cli/cli.sh $*" </dev/tty
LAUNCHER_EOF

chmod +x "$LAUNCHER_SCRIPT"

# Try to create symlink in /usr/local/bin (requires sudo)
if [ -w "$BIN_DIR" ]; then
	ln -sf "$LAUNCHER_SCRIPT" "$BIN_DIR/dockflow"
	echo -e "${GREEN}✓ 'dockflow' command installed to $BIN_DIR/dockflow${NC}"
else
	echo -e "${YELLOW}Creating symlink requires sudo access...${NC}"
	if sudo ln -sf "$LAUNCHER_SCRIPT" "$BIN_DIR/dockflow" 2>/dev/null; then
		echo -e "${GREEN}✓ 'dockflow' command installed to $BIN_DIR/dockflow${NC}"
	else
		# Fallback: add to PATH via shell config
		echo -e "${YELLOW}Could not create symlink in $BIN_DIR${NC}"
		echo -e "${YELLOW}Adding $INSTALL_DIR to your PATH...${NC}"

		SHELL_CONFIG=""
		if [ -n "$ZSH_VERSION" ] || [ -f "$HOME/.zshrc" ]; then
			SHELL_CONFIG="$HOME/.zshrc"
		elif [ -n "$BASH_VERSION" ] || [ -f "$HOME/.bashrc" ]; then
			SHELL_CONFIG="$HOME/.bashrc"
		fi

		if [ -n "$SHELL_CONFIG" ]; then
			# Check if already in config
			if ! grep -q "DOCKFLOW_HOME" "$SHELL_CONFIG" 2>/dev/null; then
				echo "" >>"$SHELL_CONFIG"
				echo "# Dockflow CLI" >>"$SHELL_CONFIG"
				echo "export DOCKFLOW_HOME=\"$INSTALL_DIR\"" >>"$SHELL_CONFIG"
				echo "export PATH=\"\$DOCKFLOW_HOME:\$PATH\"" >>"$SHELL_CONFIG"
				echo -e "${GREEN}✓ Added Dockflow to PATH in $SHELL_CONFIG${NC}"
				echo -e "${YELLOW}Please run 'source $SHELL_CONFIG' or restart your terminal${NC}"
			else
				echo -e "${GREEN}✓ Dockflow already configured in $SHELL_CONFIG${NC}"
			fi
		else
			echo -e "${YELLOW}Could not detect shell configuration file${NC}"
			echo -e "${YELLOW}Please add the following to your shell profile:${NC}"
			echo -e "  export DOCKFLOW_HOME=\"$INSTALL_DIR\""
			echo -e "  export PATH=\"\$DOCKFLOW_HOME:\$PATH\""
		fi
	fi
fi

# Save branch info for updates
echo "$BRANCH" >"$INSTALL_DIR/.branch"

# Run the CLI
echo -e "${BLUE}[6/6] Starting Dockflow CLI...${NC}"
echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}  Installation complete! You can now run 'dockflow' from anywhere  ${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

cd "$INSTALL_DIR" || exit 1
exec bash -c "./cli/cli.sh $*" </dev/tty
