#!/bin/bash

# Deploy command for Dockflow CLI
# Usage: dockflow deploy <env_name> [version] [--hostname <hostname>]

# Generate a random UUID without dashes
generate_uuid() {
	if command -v uuidgen >/dev/null 2>&1; then
		uuidgen | tr -d '-' | tr '[:upper:]' '[:lower:]'
	else
		# Fallback using /dev/urandom
		tr -dc 'a-f0-9' </dev/urandom | fold -w 32 | head -n 1
	fi
}

# Generate a random project ID
generate_project_id() {
	tr -dc 'a-z0-9' </dev/urandom | fold -w 8 | head -n 1
}

# Show deploy command help
show_deploy_help() {
	cat <<EOF
$(echo -e "${GREEN}========================================================")
$(echo -e "   Deploy Command - Deploy your application")
$(echo -e "========================================================${NC}")

$(echo -e "${CYAN}USAGE:${NC}")
    dockflow deploy <env_name> [version] [OPTIONS]

$(echo -e "${CYAN}ARGUMENTS:${NC}")
    env_name                 Environment name (required, e.g., production, staging, test)
    version                  Version tag (optional, e.g., 1.0.0). If not provided, a random UUID will be used.

$(echo -e "${CYAN}OPTIONS:${NC}")
    --hostname HOSTNAME      Hostname for multi-host deployments (optional, default: main)
    --branch BRANCH          Git branch name for tracking (optional, default: current branch or 'main')
    -h, --help               Show this help message

$(echo -e "${CYAN}REQUIREMENTS:${NC}")
    A .env.dockflow file must exist in the current directory with the following variables:
    
    Required:
      <ENV>_CONNECTION       Base64-encoded connection string (from 'dockflow setup-machine')
                             Format: {"host":"...","port":22,"user":"...","privateKey":"..."}
    
    Optional:
      SKIP_DOCKER_INSTALL    Set to 'true' to skip Docker installation on target

$(echo -e "${CYAN}EXAMPLES:${NC}")
    # Deploy to production with version 1.0.0
    dockflow deploy production 1.0.0
    
    # Deploy to staging (auto-generated version)
    dockflow deploy staging
    
    # Deploy to production with specific hostname
    dockflow deploy production 2.0.0 --hostname server1
    
    # Deploy with specific branch name
    dockflow deploy production 1.0.0 --branch feature-x
    
    # Deploy to test environment
    dockflow deploy test 1.0.0-rc1

$(echo -e "${CYAN}ENVIRONMENT FILE (.env.dockflow):${NC}")
    Create a .env.dockflow file in your project root:
    
    # Production connection string (from setup-machine output)
    PRODUCTION_CONNECTION=eyJob3N0Ijoi...
    
    # Staging connection string
    STAGING_CONNECTION=eyJob3N0Ijoi...
    
    # Optional: Skip Docker installation
    SKIP_DOCKER_INSTALL=true

$(echo -e "${CYAN}NOTES:${NC}")
    • The connection string is generated by 'dockflow setup-machine'
    • Make sure .env.dockflow is in your .gitignore
    • The .deployment directory must be configured in your project
    
EOF
}

# Parse deploy command arguments
parse_deploy_args() {
	DEPLOY_ENV=""
	DEPLOY_VERSION=""
	DEPLOY_HOSTNAME="main"
	DEPLOY_BRANCH=""

	while [[ $# -gt 0 ]]; do
		case "$1" in
		-h | --help)
			show_deploy_help
			exit 0
			;;
		--hostname)
			if [[ -z "${2:-}" ]]; then
				print_error "Missing value for --hostname"
				exit 1
			fi
			DEPLOY_HOSTNAME="$2"
			shift 2
			;;
		--branch)
			if [[ -z "${2:-}" ]]; then
				print_error "Missing value for --branch"
				exit 1
			fi
			DEPLOY_BRANCH="$2"
			shift 2
			;;
		-*)
			print_error "Unknown option: $1"
			echo "Run 'dockflow deploy --help' for usage information"
			exit 1
			;;
		*)
			# Positional arguments
			if [[ -z "$DEPLOY_ENV" ]]; then
				DEPLOY_ENV="$1"
			elif [[ -z "$DEPLOY_VERSION" ]]; then
				DEPLOY_VERSION="$1"
			else
				print_error "Too many arguments: $1"
				exit 1
			fi
			shift
			;;
		esac
	done

	# Validate required arguments
	if [[ -z "$DEPLOY_ENV" ]]; then
		print_error "Environment name is required"
		echo ""
		echo "Usage: dockflow deploy <env_name> [version] [--hostname <hostname>]"
		echo "Run 'dockflow deploy --help' for more information"
		exit 1
	fi

	# Generate version if not provided
	if [[ -z "$DEPLOY_VERSION" ]]; then
		DEPLOY_VERSION=$(generate_uuid)
		print_info "No version specified, using generated UUID: $DEPLOY_VERSION"
	fi

	export DEPLOY_ENV
	export DEPLOY_VERSION
	export DEPLOY_HOSTNAME
	export DEPLOY_BRANCH
}

# Cleanup function for deploy
# shellcheck disable=SC2317
cleanup_deploy() {
	local exit_code=$?
	echo ""
	print_step "Cleaning up..."

	# Remove dockflow if it exists (in /tmp)
	if [[ -d "/tmp/dockflow" ]]; then
		rm -rf "/tmp/dockflow"
	fi

	# Remove docker_images directory if it exists (in /tmp)
	if [[ -d "/tmp/dockflow_docker_images" ]]; then
		rm -rf "/tmp/dockflow_docker_images"
	fi

	# Cleanup secrets.json (in /tmp)
	if [[ -f "/tmp/secrets.json" ]]; then
		rm -f "/tmp/secrets.json"
	fi

	print_success "Cleanup complete"
	return "$exit_code"
}

# Run the deployment
run_deploy() {
	# Set trap for cleanup on exit or interrupt
	trap cleanup_deploy EXIT

	echo -e "${GREEN}=========================================================="
	echo "   DOCKFLOW DEPLOYMENT"
	echo -e "==========================================================${NC}"
	echo ""
	echo -e "${CYAN}Environment:${NC} $DEPLOY_ENV"
	echo -e "${CYAN}Version:${NC} $DEPLOY_VERSION"
	echo -e "${CYAN}Hostname:${NC} $DEPLOY_HOSTNAME"
	echo -e "${CYAN}Project Directory:${NC} $CLI_PROJECT_DIR"
	echo ""

	# Check for .env.dockflow file
	local ENV_FILE="$CLI_PROJECT_DIR/.env.dockflow"
	if [[ ! -f "$ENV_FILE" ]]; then
		print_error "Missing .env.dockflow file in $CLI_PROJECT_DIR"
		echo ""
		echo "Please create a .env.dockflow file with your connection string:"
		echo ""
		echo "  $(echo "$DEPLOY_ENV" | tr '[:lower:]' '[:upper:]')_CONNECTION=<base64_connection_string>"
		echo ""
		echo "You can get the connection string by running 'dockflow setup-machine' on your server."
		exit 1
	fi

	# Check for .deployment directory
	if [[ ! -d "$CLI_PROJECT_DIR/.deployment" ]]; then
		print_error "Missing .deployment directory in $CLI_PROJECT_DIR"
		echo ""
		echo "Please run 'dockflow init' to initialize your project structure."
		exit 1
	fi

	# Load .env.dockflow
	print_step "Loading .env.dockflow..."
	set -a
	# shellcheck source=/dev/null
	source "$ENV_FILE"
	set +a

	# Check for required connection string
	local ENV_PREFIX
	ENV_PREFIX=$(echo "$DEPLOY_ENV" | tr '[:lower:]' '[:upper:]')
	local CONNECTION_VAR="${ENV_PREFIX}_CONNECTION"

	if [[ -z "${!CONNECTION_VAR:-}" ]]; then
		print_error "Missing ${CONNECTION_VAR} in .env.dockflow"
		echo ""
		echo "Please add the connection string for the $DEPLOY_ENV environment:"
		echo ""
		echo "  ${CONNECTION_VAR}=<base64_connection_string>"
		exit 1
	fi

	print_success "Connection string found for $DEPLOY_ENV environment"

	# Check required dependencies
	print_step "Checking dependencies..."

	if ! command -v python3 >/dev/null 2>&1; then
		print_error "python3 is required but not installed"
		exit 1
	fi

	if ! command -v ansible-playbook >/dev/null 2>&1; then
		print_error "ansible-playbook is required but not installed"
		exit 1
	fi

	if ! command -v jq >/dev/null 2>&1; then
		print_error "jq is required but not installed"
		exit 1
	fi

	# Check if pyyaml is installed
	if ! python3 -c "import yaml" 2>/dev/null; then
		print_warning "pyyaml is not installed, installing..."
		pip3 install pyyaml --quiet
	fi

	# Check if decomposerize is installed
	if ! command -v decomposerize >/dev/null 2>&1; then
		print_warning "decomposerize is not installed, installing..."
		npm i -g shawiizz-decomposerize --silent
	fi

	print_success "All dependencies are installed"

	# Setup environment variables
	print_step "Setting up deployment environment..."

	export ENV="$DEPLOY_ENV"
	export HOSTNAME="$DEPLOY_HOSTNAME"
	export VERSION="$DEPLOY_VERSION"
	export PROJECT_ID="auto" # Will be resolved automatically by Ansible from existing tracking files
	# Use provided branch or detect from git, fallback to 'main'
	if [[ -n "$DEPLOY_BRANCH" ]]; then
		export BRANCH_NAME="$DEPLOY_BRANCH"
	else
		BRANCH_NAME=$(timeout 2 git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "main")
		export BRANCH_NAME
	fi
	export ROOT_PATH="$CLI_PROJECT_DIR"
	export ANSIBLE_HOST_KEY_CHECKING=False

	# Create secrets.json from .env.dockflow variables
	print_step "Creating secrets configuration..."
	local SECRETS_FILE="/tmp/secrets.json"

	# Build secrets JSON from environment
	python3 <<PYTHON_EOF
import json
import os

secrets = {}
env_prefix = "${ENV_PREFIX}_"

for key, value in os.environ.items():
    if key.startswith(env_prefix) or key in ['SKIP_DOCKER_INSTALL']:
        secrets[key] = value

with open("$SECRETS_FILE", 'w') as f:
    json.dump(secrets, f)

print(f"Created secrets.json with {len(secrets)} variables")
PYTHON_EOF

	# Use dockflow from container (/tmp/dockflow)
	local DOCKFLOW_DIR="/tmp/dockflow"

	# Run deployment
	print_step "Starting deployment..."
	echo ""

	cd "$CLI_PROJECT_DIR" || exit 1

	# Source load_env and run deployment
	source "$DOCKFLOW_DIR/.common/scripts/load_env.sh" "$ENV" "$HOSTNAME"

	echo ""
	print_step "Running Ansible deployment..."
	echo ""

	bash "$DOCKFLOW_DIR/.common/scripts/deploy_with_ansible.sh"
	local DEPLOY_STATUS=$?

	if [[ $DEPLOY_STATUS -eq 0 ]]; then
		echo ""
		echo -e "${GREEN}=========================================================="
		echo "   DEPLOYMENT SUCCESSFUL"
		echo -e "==========================================================${NC}"
		echo ""
		echo -e "${CYAN}Environment:${NC} $DEPLOY_ENV"
		echo -e "${CYAN}Version:${NC} $DEPLOY_VERSION"
		echo -e "${CYAN}Hostname:${NC} $DEPLOY_HOSTNAME"
		echo ""
	else
		echo ""
		print_error "Deployment failed with exit code $DEPLOY_STATUS"
		exit $DEPLOY_STATUS
	fi
}

export -f generate_uuid
export -f generate_project_id
export -f show_deploy_help
export -f parse_deploy_args
export -f run_deploy
