services:
  latest-tag:
    image: nginx:latest
  untagged:
    image: nginx
  pinned-tag:
    image: nginx:1.2
  digest-pin:
    image: nginx@sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
  always-pull:
    image: nginx:1.2
    pull_policy: always
