// batch/v1 Job (DESIGN-CORE 4.1; design-02 4.6, design-03 5.4.4 and 9.3).

import type { PodTemplateSpec } from './core';
import type { Condition, KubeObjectBase, LabelSelector } from './meta';

export interface JobSpec {
  template: PodTemplateSpec;
  backoffLimit?: number;
  /** immutable for non-indexed Jobs, so always stated (emission rule 8) */
  completions?: number;
  parallelism?: number;
  /**
   * Read only: generated by the Job controller together with the controller-uid pod label.
   * Never emitted, which is why an existing Job is never re-applied (kubernetes#118645).
   */
  selector?: LabelSelector;
}

export interface JobStatus {
  active?: number;
  succeeded?: number;
  failed?: number;
  ready?: number;
  startTime?: string;
  completionTime?: string;
  /** Complete, SuccessCriteriaMet, Failed, FailureTarget */
  conditions?: Condition[];
}

export interface Job extends KubeObjectBase<'batch/v1', 'Job'> {
  spec: JobSpec;
  status?: JobStatus;
}
