#!/bin/bash
# E2E test runner for DockFlow framework
# Simulates a CI/CD deployment process


IFS=$'\n\t'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export ROOT_PATH="$(cd "${SCRIPT_DIR}/../../.." && pwd)"

cd "$ROOT_PATH"

echo "Running DockFlow E2E Tests"
echo ""

# Check if test VM is running
if ! docker ps | grep -q "dockflow-test-vm"; then
    echo "ERROR: Test VM is not running. Run setup.sh first."
    exit 1
fi

echo "Setting up CI/CD environment simulation..."

# Load commit info
set -a
source dockflow/testing/e2e/test-app/.deployment/e2e-test/.commit_info
set +a

echo "Loading test environment variables..."

# Read connection string from file (generated by CLI tests)
if [ -f "/ssh-keys/connection_string" ]; then
    CONNECTION_STRING=$(cat /ssh-keys/connection_string)
    echo "Found connection string."
else
    echo "ERROR: Connection string file not found at /ssh-keys/connection_string"
    exit 1
fi

# Generate secrets.json with TEST_CONNECTION
# We use TEST_CONNECTION because ENV=test in .commit_info
echo "{\"TEST_CONNECTION\":\"$CONNECTION_STRING\"}" > secrets.json

source dockflow/.common/scripts/load_env.sh "$ENV" "$HOSTNAME"
bash dockflow/.common/scripts/deploy_with_ansible.sh

echo "Verifying deployment..."

# Wait a bit for services to start
sleep 5

# Check if container is running using docker exec
echo "Checking container status..."
if docker exec dockflow-test-vm docker ps --filter name=test-web-app --format '{{.Names}}' | grep -q "test-web-app"; then
    echo "Container is running."
else
    echo "ERROR: Container is not running."
    exit 1
fi

# Check if web app is accessible using docker exec (verbose output)
echo "Checking web application accessibility..."
RESPONSE=$(docker exec dockflow-test-vm curl -sf http://localhost:8080/ 2>&1)
if echo "$RESPONSE" | grep -q "DOCKFLOW_E2E_TEST_APP_DEPLOYED"; then
    echo "✓ Web application is accessible and serving the correct content."
else
    echo "ERROR: Web application is not serving the expected content."
    echo "Response received:"
    echo "$RESPONSE"
    echo ""
    echo "Verbose curl output:"
    docker exec dockflow-test-vm curl -v http://localhost:8080/
    exit 1
fi

echo ""
echo "All E2E tests passed."
echo ""
echo "Deployment Summary:"
echo "   Environment: ${ENV}"
echo "   Version: ${VERSION}"
echo "   Application: test-web-app"
echo ""
echo "To cleanup: cd ${SCRIPT_DIR} && bash teardown.sh"
