/**
 * Build script for cross-platform compilation
 * 
 * If the Angular UI has been built (ui/dist/browser/browser exists),
 * it generates a manifest to embed the UI assets into the compiled binary.
 * 
 * The UI must be built separately before running this script:
 *   cd ui && npm install && npm run build
 * 
 * In CI, this is handled by the build-cli.yml workflow.
 */

import { $ } from 'bun';
import { existsSync, mkdirSync, readdirSync, statSync, unlinkSync } from 'fs';
import { join, relative } from 'path';

const targets = [
  // Use baseline for broader CPU compatibility (no AVX2 requirement)
  { name: 'linux-x64', target: 'bun-linux-x64-baseline', output: 'dockflow-linux-x64' },
  { name: 'linux-arm64', target: 'bun-linux-arm64', output: 'dockflow-linux-arm64' },
  { name: 'windows-x64', target: 'bun-windows-x64-baseline', output: 'dockflow-windows-x64.exe' },
  { name: 'macos-x64', target: 'bun-darwin-x64-baseline', output: 'dockflow-macos-x64' },
  { name: 'macos-arm64', target: 'bun-darwin-arm64', output: 'dockflow-macos-arm64' },
];

const UI_DIST_PATH = join(import.meta.dir, '../ui/dist/browser/browser');

/**
 * Recursively collect all files in a directory
 */
function collectFiles(dir: string): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(dir)) {
    const fullPath = join(dir, entry);
    if (statSync(fullPath).isDirectory()) {
      files.push(...collectFiles(fullPath));
    } else {
      files.push(fullPath);
    }
  }
  return files;
}

/**
 * Generate a manifest file that imports all UI assets for embedding
 */
async function generateUIManifest(): Promise<boolean> {
  if (!existsSync(UI_DIST_PATH)) {
    console.log('⚠️  UI not built (ui/dist/browser/browser not found)');
    console.log('   Binary will be built without embedded UI.\n');
    console.log('   To include the UI, build it first:');
    console.log('   cd ui && npm install && npm run build\n');
    return false;
  }

  const files = collectFiles(UI_DIST_PATH);
  if (files.length === 0) return false;

  const imports: string[] = [];
  const entries: string[] = [];

  for (let i = 0; i < files.length; i++) {
    const relPath = relative(join(import.meta.dir, '../src'), files[i]).replace(/\\/g, '/');
    imports.push(`import asset${i} from "${relPath}" with { type: "file" };`);
    
    const urlPath = '/' + relative(UI_DIST_PATH, files[i]).replace(/\\/g, '/');
    entries.push(`  ["${urlPath}", asset${i}]`);
  }

  const manifest = `// Auto-generated UI asset manifest - DO NOT EDIT
// Generated by scripts/build.ts at compile time
${imports.join('\n')}

export const UI_ASSETS = new Map<string, string>([\n${entries.join(',\n')}\n]);
`;

  const manifestPath = join(import.meta.dir, '../src/ui-manifest.generated.ts');
  await Bun.write(manifestPath, manifest);
  console.log(`📋 Generated UI manifest with ${files.length} embedded files\n`);
  return true;
}

async function build() {
  console.log('🚀 Building Dockflow CLI...\n');

  if (!existsSync('dist')) {
    mkdirSync('dist');
  }

  // Generate UI manifest for embedding (if UI was built)
  const manifestGenerated = await generateUIManifest();

  // Get target from command line or build all
  const targetArg = process.argv[2];
  const targetsToBuild = targetArg
    ? targets.filter(t => t.name === targetArg || t.target === targetArg)
    : targets;

  if (targetsToBuild.length === 0) {
    console.error(`Unknown target: ${targetArg}`);
    console.log('Available targets:', targets.map(t => t.name).join(', '));
    process.exit(1);
  }

  for (const { name, target, output } of targetsToBuild) {
    console.log(`📦 Building for ${name}...`);
    
    try {
      await $`bun build src/index.ts --compile --target=${target} --outfile=dist/${output} --minify`;
      console.log(`   ✅ dist/${output}`);
    } catch (error) {
      console.error(`   ❌ Failed to build for ${name}:`, error);
    }
  }

  // Clean up generated manifest
  if (manifestGenerated) {
    const manifestPath = join(import.meta.dir, '../src/ui-manifest.generated.ts');
    if (existsSync(manifestPath)) unlinkSync(manifestPath);
  }

  console.log('\n✨ Build complete!');
  console.log('\nBuilt binaries:');
  
  for (const { output } of targetsToBuild) {
    const path = `dist/${output}`;
    if (existsSync(path)) {
      const file = Bun.file(path);
      const size = await file.size;
      const sizeMB = (size / 1024 / 1024).toFixed(2);
      console.log(`  - ${output} (${sizeMB} MB)`);
    }
  }
}

build();
