#!/usr/bin/env bun
/**
 * Pins what Dockflow installs for Kubernetes (k3s, Helm, the Traefik chart and image) and generates
 * the files that carry those pins (DESIGN-CORE 8.7, design-04 2.14.1 and I14):
 *   src/services/orchestrator/kubernetes/k3s/versions.ts
 *   src/services/orchestrator/kubernetes/versions.ts
 *   src/services/orchestrator/kubernetes/traefik-crd-schema.generated.ts
 * and the `k3s-pins` region of the k3s setup docs page when that page exists.
 *
 * Usage (from cli/):
 *   bun run scripts/pin-kubernetes.ts --k3s <v> [--helm <v>] [--traefik-chart <v>] [--minimum-server <v>]
 *                                     [--repin-image] [--no-docs] [--check]
 *   bun run scripts/pin-kubernetes.ts --verify
 *   bun run scripts/pin-kubernetes.ts --check-updates [--markdown]
 *   bun run scripts/pin-kubernetes.ts --resolve-channel <minimum|latest|stable>
 *
 * A version left out keeps its committed value. Checksums come from two sources that must agree:
 * k3s binaries from the release's sha256sum-<arch>.txt (re-hashed by --verify), Helm archives from
 * their .sha256sum file and a local re-hash, the chart from the repository index digest and a local
 * re-hash, the image index from the registry digest header and a hash of the served index; install.sh
 * is only published as a file and is hashed locally. A sha256 that changes while its version does not
 * is refused. --check regenerates everything in memory and exits 1 with a diff when a committed file
 * differs; --verify does the same for the committed versions and re-downloads the k3s binaries.
 * The Traefik image tag is mutable (official images are rebuilt when their base image changes): a
 * committed digest the registry still serves for the same Traefik version is kept unless
 * --repin-image is given.
 */

import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { gunzipSync } from 'node:zlib';
import { parseAllDocuments, parse as parseYaml } from 'yaml';

const CLI_DIR = resolve(import.meta.dir, '..');
const REPO_DIR = resolve(CLI_DIR, '..');
const K8S_DIR = join(CLI_DIR, 'src', 'services', 'orchestrator', 'kubernetes');
const K3S_VERSIONS_FILE = join(K8S_DIR, 'k3s', 'versions.ts');
const VERSIONS_FILE = join(K8S_DIR, 'versions.ts');
const CRD_SCHEMA_FILE = join(K8S_DIR, 'traefik-crd-schema.generated.ts');
const DOCS_PAGE = join(REPO_DIR, 'docs', 'app', 'en', 'configuration', 'kubernetes', 'setup', 'page.mdx');

const ARCHES = ['amd64', 'arm64'] as const;
type Arch = (typeof ARCHES)[number];

const K3S_RELEASES = 'https://github.com/k3s-io/k3s/releases/download';
const K3S_SOURCES = 'https://raw.githubusercontent.com/k3s-io/k3s';
const K3S_CHANNELS = 'https://update.k3s.io/v1-release/channels';
const K3S_BINARY: Record<Arch, string> = { amd64: 'k3s', arm64: 'k3s-arm64' };
const HELM_DOWNLOADS = 'https://get.helm.sh';
const HELM_LATEST_RELEASE = 'https://api.github.com/repos/helm/helm/releases/latest';
const TRAEFIK_REPO = 'https://traefik.github.io/charts';
const TRAEFIK_CHART = 'traefik';
const MIDDLEWARE_CRD_FILE = 'crds/traefik.io_middlewares.yaml';
const MIDDLEWARE_CRD_NAME = 'middlewares.traefik.io';
const REGISTRY = 'https://registry-1.docker.io';
const TRAEFIK_IMAGE_REPOSITORY = 'library/traefik';
const REGISTRY_TOKEN_URL = `https://auth.docker.io/token?service=registry.docker.io&scope=repository:${TRAEFIK_IMAGE_REPOSITORY}:pull`;
const IMAGE_INDEX_TYPES = 'application/vnd.oci.image.index.v1+json, application/vnd.docker.distribution.manifest.list.v2+json';
const REQUEST_TIMEOUT_MS = 300_000;

const GENERATED_HEADER = [
  '// Generated by cli/scripts/pin-kubernetes.ts; do not edit.',
  '// Refresh from cli/: bun run scripts/pin-kubernetes.ts --k3s <version> --helm <version> --traefik-chart <version>',
].join('\n');
const DOCS_BEGIN = '{/* BEGIN GENERATED: k3s-pins (cli/scripts/pin-kubernetes.ts) */}';
const DOCS_END = '{/* END GENERATED: k3s-pins */}';

const K3S_VERSION_RE = /^v\d+\.\d+\.\d+\+k3s\d+$/;
const PLAIN_VERSION_RE = /^v\d+\.\d+\.\d+$/;
const CHART_VERSION_RE = /^\d+\.\d+\.\d+$/;
const SHA256_RE = /^[0-9a-f]{64}$/;
const DIGEST_RE = /^sha256:[0-9a-f]{64}$/;
const IDENTIFIER_RE = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

const USAGE = `Usage (from cli/):
  bun run scripts/pin-kubernetes.ts --k3s <v> [--helm <v>] [--traefik-chart <v>] [--minimum-server <v>]
                                    [--repin-image] [--no-docs] [--check]
  bun run scripts/pin-kubernetes.ts --verify
  bun run scripts/pin-kubernetes.ts --check-updates [--markdown]
  bun run scripts/pin-kubernetes.ts --resolve-channel <minimum|latest|stable>

  --k3s, --helm, --traefik-chart  versions to pin; a version left out keeps its committed value
  --minimum-server <v>            oldest k3s server version supported (default: the committed one)
  --repin-image                   adopt the current digest of the Traefik image tag even when the
                                  committed digest is still served
  --no-docs                       leave the k3s-pins region of the setup docs page alone
  --check                         regenerate in memory, print a diff and exit 1 when a file differs
  --verify                        --check for the committed versions, plus a re-hash of the k3s binaries
  --check-updates [--markdown]    report newer k3s, Helm and Traefik releases
  --resolve-channel <channel>     print the k3s version of a channel (minimum = latest patch of the
                                  minimum server minor)
`;

class PinError extends Error {}
class UsageError extends Error {}

interface Download {
  url: string;
  sha256: string;
}

interface K3sPins {
  version: string;
  minimumServerVersion: string;
  installScript: Download;
  binaries: Record<Arch, Download>;
}

interface HelmPins {
  version: string;
  archives: Record<Arch, Download>;
}

interface TraefikPins {
  chart: string;
  repo: string;
  version: string;
  url: string;
  sha256: string;
  appVersion: string;
  imageDigest?: string;
}

interface Pins {
  k3s: K3sPins;
  helm: HelmPins;
  traefik: TraefikPins;
}

interface Committed {
  k3s?: K3sPins;
  helm?: HelmPins;
  traefik?: TraefikPins;
}

interface Output {
  path: string;
  content: string;
}

type Mode = 'pin' | 'verify' | 'check-updates' | 'resolve-channel';

interface Options {
  mode: Mode;
  help: boolean;
  k3s?: string;
  helm?: string;
  traefikChart?: string;
  minimumServer?: string;
  channel?: string;
  check: boolean;
  noDocs: boolean;
  repinImage: boolean;
  markdown: boolean;
}

type CrdType = 'string' | 'integer' | 'number' | 'boolean' | 'int-or-string' | 'array' | 'object' | 'any';

interface CrdNode {
  canonical: string;
  type: CrdType;
  items?: CrdNode;
  additionalProperties?: CrdNode;
  properties?: Record<string, CrdNode>;
}

interface MiddlewareSchema {
  apiVersion: string;
  types: Record<string, CrdNode>;
}

interface ChartResolution {
  pin: TraefikPins;
  files: Map<string, Uint8Array>;
}

// ---------------------------------------------------------------------------------------------
// Arguments

const VALUE_FLAGS = new Set(['--k3s', '--helm', '--traefik-chart', '--minimum-server', '--resolve-channel']);
const BOOLEAN_FLAGS = new Set(['--check', '--verify', '--check-updates', '--markdown', '--no-docs', '--repin-image', '--help']);
const PIN_FLAGS = ['--k3s', '--helm', '--traefik-chart', '--minimum-server', '--check', '--no-docs', '--repin-image'];
const EXCLUSIVE_FLAGS = ['--verify', '--check-updates', '--resolve-channel'];
const CHANNELS = ['minimum', 'latest', 'stable'];

function parseArgs(argv: string[]): Options {
  const values = new Map<string, string>();
  const flags = new Set<string>();
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    const eq = arg.indexOf('=');
    const name = eq > 0 ? arg.slice(0, eq) : arg;
    if (VALUE_FLAGS.has(name)) {
      const value = eq > 0 ? arg.slice(eq + 1) : argv[++i];
      if (value === undefined || value === '' || value.startsWith('--')) throw new UsageError(`${name} needs a value`);
      if (values.has(name)) throw new UsageError(`${name} is given twice`);
      values.set(name, value);
    } else if (BOOLEAN_FLAGS.has(arg)) {
      flags.add(arg);
    } else {
      throw new UsageError(`Unknown argument ${arg}`);
    }
  }
  const given = (flag: string): boolean => flags.has(flag) || values.has(flag);
  const exclusive = EXCLUSIVE_FLAGS.filter(given);
  const pinFlags = PIN_FLAGS.filter(given);
  if (exclusive.length > 1) throw new UsageError(`${exclusive.join(' and ')} cannot be combined`);
  if (exclusive.length === 1 && pinFlags.length > 0) {
    throw new UsageError(`${pinFlags[0]} cannot be combined with ${exclusive[0]}`);
  }
  if (flags.has('--markdown') && exclusive[0] !== '--check-updates') {
    throw new UsageError('--markdown only applies to --check-updates');
  }
  const channel = values.get('--resolve-channel');
  if (channel !== undefined && !CHANNELS.includes(channel)) {
    throw new UsageError(`--resolve-channel takes one of ${CHANNELS.join(', ')}, not ${channel}`);
  }
  const help = flags.has('--help');
  let mode: Mode = 'pin';
  if (exclusive[0] === '--verify') mode = 'verify';
  else if (exclusive[0] === '--check-updates') mode = 'check-updates';
  else if (exclusive[0] === '--resolve-channel') mode = 'resolve-channel';
  else if (pinFlags.length === 0 && !help) throw new UsageError('Nothing to do');
  return {
    mode,
    help,
    k3s: values.get('--k3s'),
    helm: values.get('--helm'),
    traefikChart: values.get('--traefik-chart'),
    minimumServer: values.get('--minimum-server'),
    channel,
    check: flags.has('--check'),
    noDocs: flags.has('--no-docs'),
    repinImage: flags.has('--repin-image'),
    markdown: flags.has('--markdown'),
  };
}

// ---------------------------------------------------------------------------------------------
// Small helpers

function out(text: string): void {
  process.stdout.write(text.endsWith('\n') ? text : `${text}\n`);
}

function err(text: string): void {
  process.stderr.write(text.endsWith('\n') ? text : `${text}\n`);
}

function step(text: string): void {
  err(`- ${text}`);
}

function sha256Hex(bytes: Uint8Array): string {
  return createHash('sha256').update(bytes).digest('hex');
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function asRecord(value: unknown, what: string): Record<string, unknown> {
  if (!isRecord(value)) throw new PinError(`${what} is not a mapping`);
  return value;
}

function compareCodeUnits(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0;
}

function versionParts(version: string): [number, number, number] {
  const match = /^v?(\d+)\.(\d+)\.(\d+)/.exec(version);
  if (!match) throw new PinError(`${version} is not a version`);
  return [Number(match[1]), Number(match[2]), Number(match[3])];
}

function compareVersions(a: string, b: string): number {
  const x = versionParts(a);
  const y = versionParts(b);
  for (let i = 0; i < 3; i++) if (x[i] !== y[i]) return x[i] - y[i];
  return 0;
}

/** k3s channel id of a version's minor, e.g. `v1.34` */
function minorChannel(version: string): string {
  const [major, minor] = versionParts(version);
  return `v${major}.${minor}`;
}

function repoPath(path: string): string {
  return relative(REPO_DIR, path).split('\\').join('/');
}

function quote(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function propertyKey(name: string): string {
  return IDENTIFIER_RE.test(name) ? name : quote(name);
}

// ---------------------------------------------------------------------------------------------
// HTTP

/** Retries transport failures, 429 and 5xx; any other answer is returned to the caller. */
async function request(url: string, init: RequestInit = {}): Promise<Response> {
  if (!url.startsWith('https://')) throw new PinError(`Refusing to download ${url} over a non-HTTPS URL`);
  const headers = new Headers(init.headers);
  if (!headers.has('User-Agent')) headers.set('User-Agent', 'dockflow-pin-kubernetes');
  let failure = '';
  for (let attempt = 1; attempt <= 3; attempt++) {
    try {
      const response = await fetch(url, { ...init, headers, redirect: 'follow', signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS) });
      if (response.status !== 429 && response.status < 500) return response;
      failure = `HTTP ${response.status}`;
    } catch (error) {
      failure = error instanceof Error ? error.message : String(error);
    }
    if (attempt < 3) await Bun.sleep(attempt * 2000);
  }
  throw new PinError(`${init.method ?? 'GET'} ${url} failed: ${failure}`);
}

async function fetchOk(url: string, init: RequestInit = {}): Promise<Response> {
  const response = await request(url, init);
  if (!response.ok) throw new PinError(`${init.method ?? 'GET'} ${url} answered HTTP ${response.status}`);
  return response;
}

async function fetchText(url: string, init: RequestInit = {}): Promise<string> {
  return (await fetchOk(url, init)).text();
}

async function fetchBytes(url: string): Promise<Uint8Array> {
  return new Uint8Array(await (await fetchOk(url)).arrayBuffer());
}

// ---------------------------------------------------------------------------------------------
// Checksum files and archives

/** `<sha256>  <name>` lines (sha256sum output); a name listed twice with two hashes is refused. */
function parseChecksums(text: string, source: string): Map<string, string> {
  const sums = new Map<string, string>();
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (line === '') continue;
    const match = /^([0-9A-Fa-f]{64})\s+\*?(\S.*)$/.exec(line);
    if (!match) throw new PinError(`${source}: unexpected line "${line}"`);
    const hash = match[1].toLowerCase();
    const name = match[2];
    const previous = sums.get(name);
    if (previous !== undefined && previous !== hash) throw new PinError(`${source} lists ${name} twice with different hashes`);
    sums.set(name, hash);
  }
  return sums;
}

const decoder = new TextDecoder();

function cString(bytes: Uint8Array): string {
  const end = bytes.indexOf(0);
  return decoder.decode(end < 0 ? bytes : bytes.subarray(0, end));
}

function tarSize(field: Uint8Array, name: string): number {
  if ((field[0] & 0x80) !== 0) throw new PinError(`${name}: base-256 tar sizes are not supported`);
  const text = cString(field).trim();
  const size = text === '' ? 0 : Number.parseInt(text, 8);
  if (!Number.isFinite(size)) throw new PinError(`${name}: invalid tar size field`);
  return size;
}

/** `<length> <key>=<value>\n` records of a PAX extended header */
function paxRecords(data: Uint8Array): Map<string, string> {
  const records = new Map<string, string>();
  let offset = 0;
  while (offset < data.length) {
    const space = data.indexOf(0x20, offset);
    if (space < 0) break;
    const length = Number.parseInt(decoder.decode(data.subarray(offset, space)), 10);
    if (!Number.isFinite(length) || length <= 0) break;
    const record = decoder.decode(data.subarray(space + 1, offset + length - 1));
    const eq = record.indexOf('=');
    if (eq > 0) records.set(record.slice(0, eq), record.slice(eq + 1));
    offset += length;
  }
  return records;
}

/** Regular files of a gzipped tar archive, keyed by path (ustar, GNU long names and PAX paths). */
function readTarGz(archive: Uint8Array, name: string): Map<string, Uint8Array> {
  const tar = new Uint8Array(gunzipSync(archive));
  const files = new Map<string, Uint8Array>();
  let offset = 0;
  let longName: string | null = null;
  let paxPath: string | null = null;
  while (offset + 512 <= tar.length) {
    const header = tar.subarray(offset, offset + 512);
    if (header.every((byte) => byte === 0)) break;
    const size = tarSize(header.subarray(124, 136), name);
    const type = String.fromCharCode(header[156]);
    const data = tar.subarray(offset + 512, offset + 512 + size);
    offset += 512 + Math.ceil(size / 512) * 512;
    if (type === 'x') {
      paxPath = paxRecords(data).get('path') ?? null;
      continue;
    }
    if (type === 'L') {
      longName = cString(data);
      continue;
    }
    if (type === 'g') continue;
    const prefix = cString(header.subarray(345, 500));
    const entry = paxPath ?? longName ?? (prefix === '' ? cString(header.subarray(0, 100)) : `${prefix}/${cString(header.subarray(0, 100))}`);
    paxPath = null;
    longName = null;
    if (type === '0' || type === '\0' || type === '7') files.set(entry, data);
  }
  return files;
}

function fileText(files: Map<string, Uint8Array>, path: string, archive: string): string {
  const data = files.get(path);
  if (!data) throw new PinError(`${archive} has no ${path}`);
  return decoder.decode(data);
}

// ---------------------------------------------------------------------------------------------
// Resolution

async function k3sBinary(version: string, arch: Arch): Promise<Download> {
  const tag = encodeURIComponent(version);
  const listing = `sha256sum-${arch}.txt`;
  const source = `${listing} of k3s ${version}`;
  const sums = parseChecksums(await fetchText(`${K3S_RELEASES}/${tag}/${listing}`), source);
  const name = K3S_BINARY[arch];
  const sha256 = sums.get(name);
  if (sha256 === undefined) throw new PinError(`${source} has no entry for ${name}`);
  return { url: `${K3S_RELEASES}/${tag}/${name}`, sha256 };
}

async function resolveK3s(version: string, minimumServerVersion: string): Promise<K3sPins> {
  step(`k3s ${version}`);
  const binaries: Record<Arch, Download> = {
    amd64: await k3sBinary(version, 'amd64'),
    arm64: await k3sBinary(version, 'arm64'),
  };
  const url = `${K3S_SOURCES}/${encodeURIComponent(version)}/install.sh`;
  const installScript = { url, sha256: sha256Hex(await fetchBytes(url)) };
  return { version, minimumServerVersion, installScript, binaries };
}

async function helmArchive(version: string, arch: Arch): Promise<Download> {
  const name = `helm-${version}-linux-${arch}.tar.gz`;
  const url = `${HELM_DOWNLOADS}/${name}`;
  const sums = parseChecksums(await fetchText(`${url}.sha256sum`), `${name}.sha256sum`);
  const published = sums.get(name);
  if (published === undefined) throw new PinError(`${name}.sha256sum has no entry for ${name}`);
  const actual = sha256Hex(await fetchBytes(url));
  if (actual !== published) {
    throw new PinError(`${name}: ${name}.sha256sum says ${published}, the downloaded archive hashes to ${actual}`);
  }
  return { url, sha256: published };
}

async function resolveHelm(version: string): Promise<HelmPins> {
  step(`Helm ${version}`);
  return { version, archives: { amd64: await helmArchive(version, 'amd64'), arm64: await helmArchive(version, 'arm64') } };
}

async function chartIndexEntries(): Promise<unknown[]> {
  const index = asRecord(parseYaml(await fetchText(`${TRAEFIK_REPO}/index.yaml`)), `${TRAEFIK_REPO}/index.yaml`);
  const entries = asRecord(index.entries, `${TRAEFIK_REPO}/index.yaml entries`)[TRAEFIK_CHART];
  if (!Array.isArray(entries)) throw new PinError(`${TRAEFIK_REPO}/index.yaml lists no ${TRAEFIK_CHART} chart`);
  return entries;
}

async function resolveTraefikChart(version: string): Promise<ChartResolution> {
  step(`Traefik chart ${version}`);
  const entry = (await chartIndexEntries()).find((candidate) => isRecord(candidate) && candidate.version === version);
  if (!isRecord(entry)) throw new PinError(`${TRAEFIK_REPO}/index.yaml has no ${TRAEFIK_CHART} ${version}`);
  const urls: unknown = entry.urls;
  const listed = Array.isArray(urls) && typeof urls[0] === 'string' ? urls[0] : null;
  const digest = entry.digest;
  const appVersion = entry.appVersion;
  if (listed === null || typeof digest !== 'string' || !SHA256_RE.test(digest) || typeof appVersion !== 'string') {
    throw new PinError(`The index entry of ${TRAEFIK_CHART} ${version} lacks urls, a sha256 digest or appVersion`);
  }
  if (!PLAIN_VERSION_RE.test(appVersion)) throw new PinError(`${TRAEFIK_CHART} ${version} has appVersion ${appVersion}, not a vX.Y.Z tag`);
  const url = new URL(listed, `${TRAEFIK_REPO}/`).href;
  const archiveName = `${TRAEFIK_CHART}-${version}.tgz`;
  const archive = await fetchBytes(url);
  const sha256 = sha256Hex(archive);
  if (sha256 !== digest) {
    throw new PinError(`${archiveName}: the repository index digest is ${digest}, the downloaded archive hashes to ${sha256}`);
  }
  const files = readTarGz(archive, archiveName);
  const chartYaml = asRecord(parseYaml(fileText(files, `${TRAEFIK_CHART}/Chart.yaml`, archiveName)), `${archiveName} Chart.yaml`);
  if (chartYaml.version !== version || chartYaml.appVersion !== appVersion) {
    throw new PinError(
      `${archiveName}: Chart.yaml says version ${String(chartYaml.version)} appVersion ${String(chartYaml.appVersion)}, the repository index says ${version} ${appVersion}`,
    );
  }
  return { pin: { chart: TRAEFIK_CHART, repo: TRAEFIK_REPO, version, url, sha256, appVersion }, files };
}

async function registryToken(): Promise<string> {
  const body: unknown = JSON.parse(await fetchText(REGISTRY_TOKEN_URL));
  const token = isRecord(body) ? body.token : undefined;
  if (typeof token !== 'string' || token === '') throw new PinError(`Docker Hub returned no anonymous pull token for ${TRAEFIK_IMAGE_REPOSITORY}`);
  return token;
}

function registryHeaders(token: string): Record<string, string> {
  return { Authorization: `Bearer ${token}`, Accept: IMAGE_INDEX_TYPES };
}

async function currentTagDigest(tag: string, token: string): Promise<string> {
  const response = await fetchOk(`${REGISTRY}/v2/${TRAEFIK_IMAGE_REPOSITORY}/manifests/${tag}`, {
    method: 'HEAD',
    headers: registryHeaders(token),
  });
  const digest = response.headers.get('docker-content-digest');
  if (digest === null || !DIGEST_RE.test(digest)) throw new PinError(`docker.io/traefik:${tag}: the registry returned no image index digest`);
  return digest;
}

function platformEntry(manifests: unknown[], arch: Arch): Record<string, unknown> | undefined {
  for (const manifest of manifests) {
    if (!isRecord(manifest) || !isRecord(manifest.platform)) continue;
    if (manifest.platform.os === 'linux' && manifest.platform.architecture === arch) return manifest;
  }
  return undefined;
}

/** Empty when the registry serves the digest as a multi-arch index of Traefik <appVersion>. */
async function imageIndexProblems(digest: string, appVersion: string, token: string): Promise<string[]> {
  const url = `${REGISTRY}/v2/${TRAEFIK_IMAGE_REPOSITORY}/manifests/${digest}`;
  const response = await request(url, { headers: registryHeaders(token) });
  if (response.status === 404) return [`docker.io/traefik@${digest} is no longer served by the registry`];
  if (!response.ok) throw new PinError(`GET ${url} answered HTTP ${response.status}`);
  const body = new Uint8Array(await response.arrayBuffer());
  const problems: string[] = [];
  const served = `sha256:${sha256Hex(body)}`;
  if (served !== digest) problems.push(`docker.io/traefik@${digest}: the registry served an index hashing to ${served}`);
  const index: unknown = JSON.parse(decoder.decode(body));
  const manifests: unknown[] = isRecord(index) && Array.isArray(index.manifests) ? index.manifests : [];
  for (const arch of ARCHES) {
    const entry = platformEntry(manifests, arch);
    if (!entry) {
      problems.push(`docker.io/traefik@${digest} has no linux/${arch} image`);
      continue;
    }
    const version = isRecord(entry.annotations) ? entry.annotations['org.opencontainers.image.version'] : undefined;
    if (version !== undefined && version !== appVersion) {
      problems.push(`docker.io/traefik@${digest} linux/${arch} is Traefik ${String(version)}, not ${appVersion}`);
    }
  }
  return problems;
}

async function resolveImageDigest(
  appVersion: string,
  committed: TraefikPins | undefined,
  repinImage: boolean,
  notes: string[],
): Promise<string> {
  step(`Traefik image ${appVersion}`);
  const token = await registryToken();
  const tagDigest = await currentTagDigest(appVersion, token);
  const kept = committed !== undefined && committed.appVersion === appVersion && !repinImage ? committed.imageDigest : undefined;
  if (kept !== undefined && kept !== tagDigest) {
    const problems = await imageIndexProblems(kept, appVersion, token);
    if (problems.length === 0) {
      notes.push(
        `docker.io/traefik:${appVersion} now resolves to ${tagDigest} (the image was rebuilt); the pinned ${kept} is still served and was kept. Pass --repin-image to adopt the rebuild.`,
      );
      return kept;
    }
    notes.push(...problems, `The pin moves to the current digest of docker.io/traefik:${appVersion}.`);
  }
  const problems = await imageIndexProblems(tagDigest, appVersion, token);
  if (problems.length > 0) throw new PinError(problems.join('; '));
  return tagDigest;
}

/** The Middleware CRD `openAPIV3Schema` of the served version, reduced to what label coercion needs. */
function middlewareSchema(chart: ChartResolution): MiddlewareSchema {
  const archiveName = `${chart.pin.chart}-${chart.pin.version}.tgz`;
  const path = `${chart.pin.chart}/${MIDDLEWARE_CRD_FILE}`;
  const crds = parseAllDocuments(fileText(chart.files, path, archiveName)).map((document) => {
    if (document.errors.length > 0) throw new PinError(`${path}: ${document.errors[0].message}`);
    return document.toJS() as unknown;
  });
  const crd = crds.find((doc) => isRecord(doc) && doc.kind === 'CustomResourceDefinition' && isRecord(doc.metadata) && doc.metadata.name === MIDDLEWARE_CRD_NAME);
  const spec = asRecord(asRecord(crd, `${path} (${MIDDLEWARE_CRD_NAME})`).spec, `${path} spec`);
  if (typeof spec.group !== 'string' || !Array.isArray(spec.versions)) throw new PinError(`${path}: spec.group or spec.versions is missing`);
  const versions: unknown[] = spec.versions;
  const served = versions.filter((version) => isRecord(version) && version.served === true && version.storage === true);
  const version = served.length === 1 ? served[0] : undefined;
  if (!isRecord(version) || typeof version.name !== 'string') throw new PinError(`${path}: expected exactly one served storage version`);
  const openApi = asRecord(asRecord(version.schema, `${path} schema`).openAPIV3Schema, `${path} openAPIV3Schema`);
  const root = toNode(asRecord(openApi.properties, `${path} properties`).spec, 'spec', 'spec');
  if (root.type !== 'object' || root.properties === undefined) throw new PinError(`${path}: spec has no properties`);
  return { apiVersion: `${spec.group}/${version.name}`, types: root.properties };
}

// Validation-only keywords: label coercion only needs names and types (design-04 2.14.1 rule 4).
const IGNORED_SCHEMA_KEYS = new Set([
  'description',
  'format',
  'enum',
  'pattern',
  'minimum',
  'maximum',
  'exclusiveMinimum',
  'exclusiveMaximum',
  'minLength',
  'maxLength',
  'minItems',
  'maxItems',
  'minProperties',
  'maxProperties',
  'uniqueItems',
  'required',
  'default',
  'nullable',
  'x-kubernetes-validations',
  'x-kubernetes-list-type',
  'x-kubernetes-list-map-keys',
  'x-kubernetes-map-type',
]);
const STRUCTURAL_SCHEMA_KEYS = new Set(['type', 'items', 'properties', 'additionalProperties', 'x-kubernetes-preserve-unknown-fields']);

function toNode(schema: unknown, canonical: string, path: string): CrdNode {
  const node = asRecord(schema, path);
  if (node['x-kubernetes-int-or-string'] === true) return { canonical, type: 'int-or-string' };
  const unsupported = Object.keys(node).filter((key) => !IGNORED_SCHEMA_KEYS.has(key) && !STRUCTURAL_SCHEMA_KEYS.has(key));
  if (unsupported.length > 0) {
    throw new PinError(`${path}: unsupported schema keyword ${unsupported.join(', ')}; extend pin-kubernetes.ts before pinning this chart`);
  }
  const preserve = node['x-kubernetes-preserve-unknown-fields'] === true;
  if (node.type === undefined && preserve && node.properties === undefined) return { canonical, type: 'any' };
  switch (node.type) {
    case 'string':
    case 'integer':
    case 'number':
    case 'boolean':
      return { canonical, type: node.type };
    case 'array':
      return { canonical, type: 'array', items: toNode(node.items, '', `${path}[]`) };
    case 'object': {
      const result: CrdNode = { canonical, type: 'object' };
      if (isRecord(node.additionalProperties)) result.additionalProperties = toNode(node.additionalProperties, '', `${path}{}`);
      else if (node.additionalProperties === true || preserve) result.additionalProperties = { canonical: '', type: 'any' };
      if (node.properties !== undefined) result.properties = toProperties(node.properties, path);
      return result;
    }
    default:
      throw new PinError(`${path}: unsupported schema type ${JSON.stringify(node.type)}`);
  }
}

function toProperties(properties: unknown, path: string): Record<string, CrdNode> {
  const record = asRecord(properties, `${path}.properties`);
  const byKey = new Map<string, string>();
  for (const name of Object.keys(record)) {
    const key = name.toLowerCase();
    const other = byKey.get(key);
    if (other !== undefined) throw new PinError(`${path}: ${other} and ${name} only differ by case, so labels cannot tell them apart`);
    byKey.set(key, name);
  }
  const result: Record<string, CrdNode> = {};
  for (const key of [...byKey.keys()].sort(compareCodeUnits)) {
    const name = byKey.get(key) ?? key;
    result[key] = toNode(record[name], name, `${path}.${name}`);
  }
  return result;
}

// ---------------------------------------------------------------------------------------------
// Rendering

function downloadLines(name: string, download: Download, indent: string): string[] {
  return [`${indent}${name}: {`, `${indent}  url: ${quote(download.url)},`, `${indent}  sha256: ${quote(download.sha256)},`, `${indent}},`];
}

function renderK3sVersions(k3s: K3sPins): string {
  return [
    GENERATED_HEADER,
    '',
    "import type { PinnedArch, PinnedDownload } from '../versions';",
    '',
    "export type { PinnedDownload } from '../versions';",
    '',
    'export interface K3sPin {',
    '  readonly version: string;',
    '  /** oldest server version this release deploys to (preflight) and upgrades from */',
    '  readonly minimumServerVersion: string;',
    '  readonly installScript: PinnedDownload;',
    '  readonly binaries: Readonly<Record<PinnedArch, PinnedDownload>>;',
    '}',
    '',
    'export const K3S_PIN = {',
    `  version: ${quote(k3s.version)},`,
    '  /** oldest server version this release deploys to (preflight) and upgrades from */',
    `  minimumServerVersion: ${quote(k3s.minimumServerVersion)},`,
    ...downloadLines('installScript', k3s.installScript, '  '),
    '  binaries: {',
    ...ARCHES.flatMap((arch) => downloadLines(arch, k3s.binaries[arch], '    ')),
    '  },',
    '} as const satisfies K3sPin;',
    '',
  ].join('\n');
}

function renderVersions(helm: HelmPins, traefik: TraefikPins): string {
  const archive = `${traefik.chart}-${traefik.version}.tgz`;
  return [
    GENERATED_HEADER,
    '',
    '/** A download fetched over HTTPS and verified against its sha256 before use (DESIGN-CORE 8.7). */',
    'export interface PinnedDownload {',
    '  readonly url: string;',
    '  readonly sha256: string;',
    '}',
    '',
    `export const PINNED_ARCHES = [${ARCHES.map(quote).join(', ')}] as const;`,
    'export type PinnedArch = (typeof PINNED_ARCHES)[number];',
    '',
    'export interface HelmPin {',
    '  readonly version: string;',
    '  readonly archives: Readonly<Record<PinnedArch, PinnedDownload>>;',
    '}',
    '',
    'export interface TraefikChartPin {',
    '  readonly chart: string;',
    '  readonly repo: string;',
    '  readonly version: string;',
    '  /** the chart archive, as the repository index lists it */',
    '  readonly url: string;',
    '  /** sha256 of the chart archive (equals the repository index digest) */',
    '  readonly sha256: string;',
    '  readonly appVersion: string;',
    '  /** index digest of docker.io/traefik:<appVersion>; the tag is mutable, the digest is not */',
    '  readonly imageDigest?: string;',
    '}',
    '',
    'export const HELM_PIN = {',
    `  version: ${quote(helm.version)},`,
    '  archives: {',
    ...ARCHES.flatMap((arch) => downloadLines(arch, helm.archives[arch], '    ')),
    '  },',
    '} as const satisfies HelmPin;',
    '',
    '// Typed rather than `as const` so a caller can pass a pin without an image digest.',
    'export const TRAEFIK_CHART_PIN: TraefikChartPin = {',
    `  chart: ${quote(traefik.chart)},`,
    `  repo: ${quote(traefik.repo)},`,
    `  version: ${quote(traefik.version)},`,
    `  url: ${quote(traefik.url)},`,
    `  /** sha256 of ${archive} (equals the repository index digest) */`,
    `  sha256: ${quote(traefik.sha256)},`,
    `  appVersion: ${quote(traefik.appVersion)},`,
    ...(traefik.imageDigest === undefined ? [] : [`  imageDigest: ${quote(traefik.imageDigest)},`]),
    '};',
    '',
  ].join('\n');
}

function isInline(node: CrdNode): boolean {
  if (node.properties !== undefined) return false;
  return (node.items === undefined || isInline(node.items)) && (node.additionalProperties === undefined || isInline(node.additionalProperties));
}

function emitNode(node: CrdNode, indent: string): string {
  const head = [`canonical: ${quote(node.canonical)}`, `type: ${quote(node.type)}`];
  if (isInline(node)) {
    const parts = [...head];
    if (node.items) parts.push(`items: ${emitNode(node.items, indent)}`);
    if (node.additionalProperties) parts.push(`additionalProperties: ${emitNode(node.additionalProperties, indent)}`);
    return `{ ${parts.join(', ')} }`;
  }
  const inner = `${indent}  `;
  const lines = ['{', ...head.map((part) => `${inner}${part},`)];
  if (node.items) lines.push(`${inner}items: ${emitNode(node.items, inner)},`);
  if (node.additionalProperties) lines.push(`${inner}additionalProperties: ${emitNode(node.additionalProperties, inner)},`);
  const entries = node.properties === undefined ? null : Object.entries(node.properties);
  if (entries !== null && entries.length === 0) lines.push(`${inner}properties: {},`);
  if (entries !== null && entries.length > 0) {
    lines.push(`${inner}properties: {`);
    for (const [key, child] of entries) lines.push(`${inner}  ${propertyKey(key)}: ${emitNode(child, `${inner}  `)},`);
    lines.push(`${inner}},`);
  }
  lines.push(`${indent}}`);
  return lines.join('\n');
}

function renderMiddlewareSchema(traefik: TraefikPins, schema: MiddlewareSchema): string {
  return [
    GENERATED_HEADER,
    '',
    '// Property map of the Middleware CRD shipped in the pinned Traefik chart, used to parse and coerce',
    '// `traefik.http.middlewares.*` labels (design-04 2.14.1).',
    '',
    '/** JSON-schema type of a CRD property; label values are coerced by it (design-04 2.14.1 rule 4). */',
    'export type CrdPropertyType =',
    "  | 'string'",
    "  | 'integer'",
    "  | 'number'",
    "  | 'boolean'",
    "  | 'int-or-string'",
    "  | 'array'",
    "  | 'object'",
    '  /** x-kubernetes-preserve-unknown-fields: any content, nothing to validate */',
    "  | 'any';",
    '',
    'export interface CrdPropertyNode {',
    '  /** property name as the CRD spells it; empty for array items and map values */',
    '  readonly canonical: string;',
    '  readonly type: CrdPropertyType;',
    '  /** element schema of an array */',
    '  readonly items?: CrdPropertyNode;',
    '  /** value schema of a map, whose keys are chosen by the user and kept as written */',
    '  readonly additionalProperties?: CrdPropertyNode;',
    '  /** named properties of an object, keyed by lowercase name */',
    '  readonly properties?: Readonly<Record<string, CrdPropertyNode>>;',
    '}',
    '',
    '/** The chart this map was extracted from; it must equal TRAEFIK_CHART_PIN. */',
    'export const MIDDLEWARE_SCHEMA_SOURCE = {',
    `  chart: ${quote(traefik.chart)},`,
    `  chartVersion: ${quote(traefik.version)},`,
    `  chartSha256: ${quote(traefik.sha256)},`,
    `  appVersion: ${quote(traefik.appVersion)},`,
    `  file: ${quote(`${traefik.chart}/${MIDDLEWARE_CRD_FILE}`)},`,
    `  apiVersion: ${quote(schema.apiVersion)},`,
    '} as const;',
    '',
    '/** Middleware types (the properties of the CRD `spec`), keyed by lowercase name. */',
    'export const MIDDLEWARE_SCHEMA: Readonly<Record<string, CrdPropertyNode>> = {',
    ...Object.entries(schema.types).map(([key, node]) => `  ${propertyKey(key)}: ${emitNode(node, '  ')},`),
    '};',
    '',
  ].join('\n');
}

function renderDocsRegion(pins: Pins): string {
  return [
    DOCS_BEGIN,
    '| Component | Version |',
    '|---|---|',
    `| k3s | \`${pins.k3s.version}\` |`,
    `| Minimum server version | \`${pins.k3s.minimumServerVersion}\` |`,
    `| Helm | \`${pins.helm.version}\` |`,
    `| Traefik chart | \`${pins.traefik.version}\` (Traefik \`${pins.traefik.appVersion}\`) |`,
    DOCS_END,
  ].join('\n');
}

/** null when the page has no complete k3s-pins region */
function replaceDocsRegion(page: string, region: string): string | null {
  const crlf = page.includes('\r\n');
  const text = crlf ? page.replace(/\r\n/g, '\n') : page;
  const start = text.indexOf(DOCS_BEGIN);
  const end = start < 0 ? -1 : text.indexOf(DOCS_END, start);
  if (start < 0 || end < 0) return null;
  const replaced = text.slice(0, start) + region + text.slice(end + DOCS_END.length);
  return crlf ? replaced.replace(/\n/g, '\r\n') : replaced;
}

function docsOutput(pins: Pins, notes: string[]): Output | null {
  if (!existsSync(DOCS_PAGE)) {
    notes.push(`${repoPath(DOCS_PAGE)} does not exist; its k3s-pins region was not generated.`);
    return null;
  }
  const content = replaceDocsRegion(readFileSync(DOCS_PAGE, 'utf8'), renderDocsRegion(pins));
  if (content === null) {
    notes.push(`${repoPath(DOCS_PAGE)} has no ${DOCS_BEGIN} ... ${DOCS_END} region; it was not generated.`);
    return null;
  }
  return { path: DOCS_PAGE, content };
}

// ---------------------------------------------------------------------------------------------
// Comparison

/** Lines removed from `before` (-) and added by `after` (+), from a longest-common-subsequence walk. */
function formatDiff(before: string, after: string, limit = 80): string {
  const a = before.split('\n');
  const b = after.split('\n');
  const common = Array.from({ length: a.length + 1 }, () => new Uint32Array(b.length + 1));
  for (let i = a.length - 1; i >= 0; i--) {
    for (let j = b.length - 1; j >= 0; j--) {
      common[i][j] = a[i] === b[j] ? common[i + 1][j + 1] + 1 : Math.max(common[i + 1][j], common[i][j + 1]);
    }
  }
  const lines: string[] = [];
  let i = 0;
  let j = 0;
  while (i < a.length || j < b.length) {
    if (i < a.length && j < b.length && a[i] === b[j]) {
      i++;
      j++;
    } else if (i < a.length && (j === b.length || common[i + 1][j] >= common[i][j + 1])) {
      lines.push(`-${i + 1}: ${a[i]}`);
      i++;
    } else {
      lines.push(`+${j + 1}: ${b[j]}`);
      j++;
    }
  }
  if (lines.length <= limit) return lines.join('\n');
  return [...lines.slice(0, limit), `... ${lines.length - limit} more changed lines`].join('\n');
}

function normalizeEol(text: string): string {
  return text.replace(/\r\n/g, '\n');
}

/** A sha256 that changed while its version did not: a re-published or tampered artifact. */
function changedUnderSameVersion(committed: Committed, pins: Pins): string[] {
  const problems: string[] = [];
  const compare = (what: string, before: string | undefined, after: string): void => {
    if (before !== undefined && before !== after) problems.push(`${what} changed without a version change: committed ${before}, published ${after}`);
  };
  const k3s = committed.k3s;
  if (k3s !== undefined && k3s.version === pins.k3s.version) {
    compare(`k3s ${k3s.version} install.sh`, k3s.installScript?.sha256, pins.k3s.installScript.sha256);
    for (const arch of ARCHES) compare(`k3s ${k3s.version} ${arch} binary`, k3s.binaries?.[arch]?.sha256, pins.k3s.binaries[arch].sha256);
  }
  const helm = committed.helm;
  if (helm !== undefined && helm.version === pins.helm.version) {
    for (const arch of ARCHES) compare(`Helm ${helm.version} ${arch} archive`, helm.archives?.[arch]?.sha256, pins.helm.archives[arch].sha256);
  }
  const traefik = committed.traefik;
  if (traefik !== undefined && traefik.version === pins.traefik.version) {
    compare(`Traefik chart ${traefik.version} archive`, traefik.sha256, pins.traefik.sha256);
  }
  return problems;
}

async function verifyK3sBinaries(k3s: K3sPins): Promise<string[]> {
  const problems: string[] = [];
  for (const arch of ARCHES) {
    const pin = k3s.binaries[arch];
    step(`re-hashing ${pin.url}`);
    const actual = sha256Hex(await fetchBytes(pin.url));
    if (actual !== pin.sha256) problems.push(`k3s ${k3s.version} ${arch}: the download hashes to ${actual}, sha256sum-${arch}.txt says ${pin.sha256}`);
  }
  return problems;
}

function reportCheck(outputs: Output[], problems: string[]): number {
  let failed = problems.length > 0;
  for (const problem of problems) out(`mismatch: ${problem}`);
  for (const output of outputs) {
    const label = repoPath(output.path);
    const committed = existsSync(output.path) ? normalizeEol(readFileSync(output.path, 'utf8')) : null;
    const expected = normalizeEol(output.content);
    if (committed === expected) {
      out(`ok       ${label}`);
      continue;
    }
    failed = true;
    if (committed === null) {
      out(`missing  ${label}`);
      continue;
    }
    out(`differs  ${label} (- committed, + regenerated)`);
    out(formatDiff(committed, expected));
  }
  out(failed ? 'The committed pins are out of date.' : 'The committed pins are up to date.');
  return failed ? 1 : 0;
}

// ---------------------------------------------------------------------------------------------
// Modes

async function importExport<T>(file: string, name: string): Promise<T | undefined> {
  if (!existsSync(file)) return undefined;
  try {
    const loaded: Record<string, unknown> = await import(pathToFileURL(file).href);
    return loaded[name] as T | undefined;
  } catch (error) {
    throw new PinError(`Could not load ${repoPath(file)}: ${error instanceof Error ? error.message : String(error)}`);
  }
}

async function loadCommitted(): Promise<Committed> {
  return {
    k3s: await importExport<K3sPins>(K3S_VERSIONS_FILE, 'K3S_PIN'),
    helm: await importExport<HelmPins>(VERSIONS_FILE, 'HELM_PIN'),
    traefik: await importExport<TraefikPins>(VERSIONS_FILE, 'TRAEFIK_CHART_PIN'),
  };
}

function checkVersions(k3s: string, minimum: string, helm: string, chart: string): void {
  if (!K3S_VERSION_RE.test(k3s)) throw new PinError(`k3s version ${k3s} is not a k3s release such as v1.36.4+k3s1`);
  if (!PLAIN_VERSION_RE.test(minimum)) throw new PinError(`minimum server version ${minimum} is not a version such as v1.34.0`);
  if (!PLAIN_VERSION_RE.test(helm)) throw new PinError(`Helm version ${helm} is not a version such as v4.3.0`);
  if (!CHART_VERSION_RE.test(chart)) throw new PinError(`Traefik chart version ${chart} is not a version such as 41.6.0`);
  if (compareVersions(minimum, k3s) > 0) throw new PinError(`The minimum server version ${minimum} is newer than k3s ${k3s}`);
}

async function runPin(options: Options): Promise<number> {
  const verify = options.mode === 'verify';
  const committed = await loadCommitted();
  const k3sVersion = options.k3s ?? committed.k3s?.version;
  const minimum = options.minimumServer ?? committed.k3s?.minimumServerVersion;
  const helmVersion = options.helm ?? committed.helm?.version;
  const chartVersion = options.traefikChart ?? committed.traefik?.version;
  if (k3sVersion === undefined) throw new UsageError('--k3s is required: there is no committed k3s pin');
  if (minimum === undefined) throw new UsageError('--minimum-server is required: there is no committed minimum server version');
  if (helmVersion === undefined) throw new UsageError('--helm is required: there is no committed Helm pin');
  if (chartVersion === undefined) throw new UsageError('--traefik-chart is required: there is no committed Traefik chart pin');
  checkVersions(k3sVersion, minimum, helmVersion, chartVersion);

  const notes: string[] = [];
  const k3s = await resolveK3s(k3sVersion, minimum);
  const helm = await resolveHelm(helmVersion);
  const chart = await resolveTraefikChart(chartVersion);
  const imageDigest = await resolveImageDigest(chart.pin.appVersion, committed.traefik, options.repinImage, notes);
  const pins: Pins = { k3s, helm, traefik: { ...chart.pin, imageDigest } };
  const schema = middlewareSchema(chart);
  const problems = changedUnderSameVersion(committed, pins);
  if (verify) problems.push(...(await verifyK3sBinaries(k3s)));

  const outputs: Output[] = [
    { path: K3S_VERSIONS_FILE, content: renderK3sVersions(k3s) },
    { path: VERSIONS_FILE, content: renderVersions(helm, pins.traefik) },
    { path: CRD_SCHEMA_FILE, content: renderMiddlewareSchema(pins.traefik, schema) },
  ];
  const docs = options.noDocs ? null : docsOutput(pins, notes);
  if (docs !== null) outputs.push(docs);
  for (const note of notes) err(`note: ${note}`);

  if (options.check || verify) return reportCheck(outputs, problems);
  if (problems.length > 0) throw new PinError(['Refusing to rewrite the pins:', ...problems.map((problem) => `  ${problem}`)].join('\n'));
  for (const output of outputs) {
    const unchanged = existsSync(output.path) && normalizeEol(readFileSync(output.path, 'utf8')) === normalizeEol(output.content);
    if (!unchanged) {
      mkdirSync(dirname(output.path), { recursive: true });
      writeFileSync(output.path, output.content);
    }
    out(`${unchanged ? 'unchanged' : 'wrote    '} ${repoPath(output.path)}`);
  }
  out(
    `Pinned k3s ${k3s.version} (minimum ${k3s.minimumServerVersion}), Helm ${helm.version}, Traefik chart ${pins.traefik.version} (Traefik ${pins.traefik.appVersion}, ${imageDigest})`,
  );
  return 0;
}

async function k3sChannels(): Promise<Map<string, string>> {
  const body = asRecord(JSON.parse(await fetchText(K3S_CHANNELS)) as unknown, K3S_CHANNELS);
  if (!Array.isArray(body.data)) throw new PinError(`${K3S_CHANNELS} has no data`);
  const channels = new Map<string, string>();
  for (const channel of body.data as unknown[]) {
    if (isRecord(channel) && typeof channel.id === 'string' && typeof channel.latest === 'string') channels.set(channel.id, channel.latest);
  }
  return channels;
}

async function resolveChannel(channel: string): Promise<number> {
  let id = channel;
  if (channel === 'minimum') {
    const committed = await loadCommitted();
    if (committed.k3s === undefined) throw new PinError('There is no committed k3s pin to read the minimum server version from');
    id = minorChannel(committed.k3s.minimumServerVersion);
  }
  const version = (await k3sChannels()).get(id);
  if (version === undefined || !K3S_VERSION_RE.test(version)) throw new PinError(`The k3s ${id} channel has no release`);
  out(version);
  return 0;
}

async function latestHelm(): Promise<string> {
  const headers: Record<string, string> = { Accept: 'application/vnd.github+json' };
  const token = process.env.GITHUB_TOKEN;
  if (token) headers.Authorization = `Bearer ${token}`;
  const body: unknown = JSON.parse(await fetchText(HELM_LATEST_RELEASE, { headers }));
  const tag = isRecord(body) ? body.tag_name : undefined;
  if (typeof tag !== 'string' || !PLAIN_VERSION_RE.test(tag)) throw new PinError(`${HELM_LATEST_RELEASE} returned no release tag`);
  return tag;
}

async function latestTraefikChart(): Promise<{ version: string; appVersion: string }> {
  let latest: { version: string; appVersion: string } | null = null;
  for (const entry of await chartIndexEntries()) {
    if (!isRecord(entry) || typeof entry.version !== 'string' || !CHART_VERSION_RE.test(entry.version)) continue;
    if (latest !== null && compareVersions(entry.version, latest.version) <= 0) continue;
    latest = { version: entry.version, appVersion: typeof entry.appVersion === 'string' ? entry.appVersion : 'unknown' };
  }
  if (latest === null) throw new PinError(`${TRAEFIK_REPO}/index.yaml lists no ${TRAEFIK_CHART} release`);
  return latest;
}

async function checkUpdates(markdown: boolean): Promise<number> {
  const committed = await loadCommitted();
  const { k3s, helm, traefik } = committed;
  if (k3s === undefined || helm === undefined || traefik === undefined) throw new PinError('--check-updates needs committed pins');
  const channels = await k3sChannels();
  const helmLatest = await latestHelm();
  const chart = await latestTraefikChart();
  const tagDigest = await currentTagDigest(traefik.appVersion, await registryToken());
  const status = (pinned: string, available: string): string => (pinned === available ? 'up to date' : 'update available');
  const rows: string[][] = [
    ['k3s (stable channel)', k3s.version, channels.get('stable') ?? 'unknown'],
    ['k3s (latest channel)', k3s.version, channels.get('latest') ?? 'unknown'],
    ['Helm', helm.version, helmLatest],
    ['Traefik chart', traefik.version, chart.version],
    [`Traefik image ${traefik.appVersion}`, traefik.imageDigest ?? 'none', tagDigest],
  ].map(([component, pinned, available]) => [component, pinned, available, status(pinned, available)]);
  if (chart.version !== traefik.version) rows[3][2] = `${chart.version} (Traefik ${chart.appVersion})`;
  if (tagDigest !== traefik.imageDigest) rows[4][3] = 'tag rebuilt (--repin-image)';
  const header = ['Component', 'Pinned', 'Available', 'Status'];
  if (markdown) {
    out('### Kubernetes pins');
    out('');
    for (const row of [header, header.map(() => '---'), ...rows]) out(`| ${row.join(' | ')} |`);
    return 0;
  }
  const widths = header.map((_, column) => Math.max(...[header, ...rows].map((row) => row[column].length)));
  for (const row of [header, ...rows]) out(row.map((cell, column) => cell.padEnd(widths[column])).join('  ').trimEnd());
  return 0;
}

async function main(argv: string[]): Promise<number> {
  const options = parseArgs(argv);
  if (options.help) {
    out(USAGE);
    return 0;
  }
  switch (options.mode) {
    case 'pin':
    case 'verify':
      return runPin(options);
    case 'check-updates':
      return checkUpdates(options.markdown);
    case 'resolve-channel':
      return resolveChannel(options.channel ?? 'stable');
  }
}

if (import.meta.main) {
  main(process.argv.slice(2)).then(
    (code) => {
      process.exitCode = code;
    },
    (error: unknown) => {
      if (error instanceof UsageError) {
        err(`${error.message}\n\n${USAGE}`);
        process.exitCode = 2;
        return;
      }
      err(`pin-kubernetes: ${error instanceof Error ? error.message : String(error)}`);
      process.exitCode = 1;
    },
  );
}
