---
- name: Configure host machine
  hosts: all
  become: yes

  tasks:
    - name: Ensure /var/lib/dockflow exists
      file:
        path: /var/lib/dockflow
        state: directory
        mode: '1777'

  roles:
    - role: geerlingguy.docker
      when: >
        not (skip_docker_install | default(false) | bool) and
        (orchestrator | default('swarm')) == 'swarm'
    - role: nginx
      tags:
        - nginx
    - role: portainer
      tags:
        - portainer
      when: (orchestrator | default('swarm')) == 'swarm'
