name: Github CI/CD

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  # Basic CI job to run on every push to branches (not used for deployment)
  build:
    if: github.ref_type == 'branch'
    uses: Shawiizz/devops-framework/.github/workflows/build.yml@1.0.37-dev16

  # Deploy your application on tag push
  deploy:
    if: github.ref_type == 'tag'
    uses: Shawiizz/devops-framework/.github/workflows/deploy.yml@1.0.37-dev16
    with:
      tag: ${{ github.ref_name }}
    secrets: inherit

  # Deploy your application on push to branch
  deploy:
    uses: Shawiizz/devops-framework/.github/workflows/deploy.yml@1.0.37-dev16
    with:
      version: ${{ github.ref_name }}-${{ github.sha }} # Note: the variable is called "version" specifically for branch deployments
    secrets: inherit