name: Github CI/CD

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

# Configuration:
# 1. Make sure your .dockflow/config.yml has project_name set:
#    project_name: "my-app"
#
# 2. Define your .dockflow/servers.yml with servers:
#    servers:
#      production:
#        main_server:
#          role: manager
#          host: your-server-ip  # Or omit and use CI secret
#
# 3. Add GitHub secrets for each server:
#    - PRODUCTION_MAIN_SERVER_CONNECTION: base64-encoded connection string
#    
#    Create connection string:
#    echo -n "user@host:22|$(cat ~/.ssh/id_rsa)" | base64

jobs:
  # Basic CI job to run on every push to branches (not used for deployment)
  build:
    if: github.ref_type == 'branch'
    uses: Shawiizz/dockflow/.github/workflows/build.yml@2.0.9
    with:
      free-disk-space: false

  # Deploy your application on tag push
  deploy-tag:
    if: github.ref_type == 'tag'
    uses: Shawiizz/dockflow/.github/workflows/deploy.yml@2.0.9
    with:
      tag: ${{ github.ref_name }}
      free-disk-space: false
    secrets: inherit

  # Deploy your application on push to branch
  deploy-branch:
    if: github.ref_type == 'branch'
    uses: Shawiizz/dockflow/.github/workflows/deploy.yml@2.0.9
    with:
      version: ${{ github.ref_name }}-${{ github.sha }}
      free-disk-space: false
    secrets: inherit