/**
 * Teardown script — stops every e2e cluster: Swarm, the k3s shared-lane project (`dockflow-k3s`,
 * every topology's compose profile plus any standalone node), the k3s setup-lane project
 * (`dockflow-k3s-setup`, fresh containers per file, including `77-identity-recovery`'s own), and the
 * bare-metal setup suite's single container.
 * Test fixtures are temp-dir copies and clean themselves up; nothing in the repo tree is generated by
 * test runs.
 *
 * Usage: bun run testing/e2e/teardown.ts
 */

import { exec, stopCluster, stopK3sCluster } from "./helpers/cluster";

await stopCluster();
await stopK3sCluster();
// Setup-suite container (plain docker run, not compose-managed)
await exec(["docker", "rm", "-f", "dockflow-test-setup"]).catch(() => {});

console.log("Teardown complete.");
