/**
 * Teardown script — stops both e2e clusters (Swarm + k3s).
 * Test fixtures are temp-dir copies and clean themselves up; nothing in the
 * repo tree is generated by test runs.
 *
 * Usage: bun run testing/e2e/teardown.ts
 */

import { stopCluster, stopK3sCluster } from "./helpers/cluster";

await stopCluster();
await stopK3sCluster();

console.log("Teardown complete.");
