name: Deploy docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy docs
        run: npx @dockflow-tools/cli deploy production ${{ github.ref_name }}-${{ github.sha }}
        env:
          DOCKFLOW_SECRETS: ${{ toJSON(secrets) }}
